### ISSUE TITLE
Try/Question: React Virtualized for Tables and Feeds

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#10]
**Design Background**: Via p6riRB-36R-p2

Tabular data in Analytics is going to be an often used design pattern in the project, and there will also be a [feed area to display notifications](https://github.com/woocommerce/woo-dash/issues/3#issuecomment-386542315) that will need to have an infinite scroll type feature as well.

In Calypso we have used [react-virtualized](https://github.com/bvaughn/react-virtualized) to display scrolling feeds of large data sets. The library also has some rich support for [tables](https://bvaughn.github.io/react-virtualized/#/components/Table) which we could absolutely leverage many features of like a static header row which headers can be clicked to sort larger data sets:

```
The table layout below is created with flexboxes. This allows it to have a fixed header and scrollable body content. It also makes use of Grid for windowing table content so that large lists are rendered efficiently
```

At first glance this seems like it could be quite useful in this project - but are there other options out there? I have worked with the library a bit and it was challenging at times, but the features are quite nice.

**Comment by belcherj** [comment]
@timmyc is this still valid?

**Comment by timmyc** [comment]
Nope Table component is all dialed in. Thanks for the old issue sweep!
