### ISSUE TITLE
Order taxes need to be synced with wc_order_tax_lookup

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1009]
Currently when orders are created, the tax information is not added to the `wc_order_tax_lookup` table.  The following fields are needed:

* tax_rate_id
* date_created
* shipping_tax
* order_tax
* total_tax

This is required for the tax report information used in the [REST API](https://github.com/woocommerce/wc-admin/pull/1000) and can probably be automatically be synced on `save_post`.

**Comment by joshuatf** [comment]
This is working as expected and can be closed.

**Comment by timmyc** [comment]
Awesome, thanks for verifying that Josh 🙇
