### ISSUE TITLE
Regenerate Report Data fails on Refunded Orders

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/wc-admin#1024]
**Describe the bug**

The report table generation fails when refunded orders are present.

```
Fatal error: Uncaught Error: Call to undefined method WC_Order_Refund::get_customer_id() in /srv/www/woocommerce/public_html/wp-content/plugins/wc-admin/includes/class-wc-admin-api-init.php:222 Stack trace: #0 /srv/www/woocommerce/public_html/wp-content/plugins/wc-admin/includes/class-wc-admin-api-init.php(157): WC_Admin_Api_Init::order_product_lookup_store_init() #1 /srv/www/woocommerce/public_html/wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-system-status-tools-v2-controller.php(560): WC_Admin_Api_Init::regenrate_report_data() #2 /srv/www/woocommerce/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(41): WC_REST_System_Status_Tools_V2_Controller->execute_tool('rebuild_stats') #3 /srv/www/woocommerce/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-status.php(34): WC_Admin_Status::status_tools() #4 /srv/www/woocommerce/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-status.php(20): include_once('/srv/www/woocom...') in /srv/www/woocommerce/public_html/wp-content/plugins/wc-admin/includes/class-wc-admin-api-init.php on line 222
```

**To Reproduce**

1. Ensure you have at least one refunded order that had items specified in the refund (click "refund" on an order and enter a quantity for one or more products in the order during the refund)
2. Go to WooCommerce > Status > Tools
3. Click "Rebuild Reports"
4. See PHP Fatal error

**Expected behavior**

No PHP Fatal 😄 

**Screenshots**

![screen shot 2018-12-07 at 9 52 58 am](https://user-images.githubusercontent.com/63922/49661304-f101af00-fa05-11e8-998b-a8e5f66630e5.png)

**Comment by joshuatf** [comment]
I'm not able to reproduce this error by "Build reports" but I am able to reproduce it on the refund page when refunding an entire item (loader spins indefinitely on refund and error log shows `Call to undefined method WC_Order_Refund::get_customer_id()`).

I think we'll want to follow a similar pattern to that of the orders table (https://github.com/woocommerce/wc-admin/issues/739) where we don't record the refund itself in the table, but we reduce the revenue amount by the respective refund amount.

We'll probably also want to remove/reduce the quantity of that product by the quantity refunded in addition to the revenue changes if:
a.  The entire order amount is refunded
b.  Or a quantity of items is inserted during refund
