### ISSUE TITLE
Summary numbers display 'N/A' instead of '0' for the previous period

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1025]
**Steps to reproduce:**
- Go to the _Orders_ report and select a period so you have no orders in the previous period. For me, selecting 'Today' in the date range worked because I didn't have any order yesterday.

**Actual result:**

- The summary numbers for the previous period will display _N/A_.

![image](https://user-images.githubusercontent.com/3616980/49663638-e995d200-fa14-11e8-8104-57e70ade4cbb.png)

**Expected result:**

- It should display _0_ and _N/A_ should only be used when we have no data for that period.

**Comment by timmyc** [comment]
This appears to be all fixed up after #1026
