### ISSUE TITLE
Customers: Country Advanced Filter

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1032]
Child Task of #175 

![image](https://user-images.githubusercontent.com/22080/49668070-e816da80-fa11-11e8-877b-3b42d848374e.png)

Create an Advanced Filter config and associated [autocompleter](https://github.com/woocommerce/wc-admin/tree/master/packages/components/src/search/autocompleters) for customer countries

@peterfabian - for the country REST API arg - is that the country code that should be passed in?

@LevinMedia when interacting with this advanced filter - should this be a type-ahead autocompleter or should we just use a select filter populated with country names?

**Comment by justinshreve** [comment]
> for the country REST API arg - is that the country code that should be passed in?

It is for other endpoints: https://github.com/woocommerce/woocommerce/blob/e1255de71709d9e7cd8caa143c56fb4d60ab7101/includes/api/class-wc-rest-customers-controller.php#L192

**Comment by LevinMedia** [comment]
Hi there @timmyc sorry for the late reply... type-ahead autocompleter would be fantastic.
