### ISSUE TITLE
Customers: Add Date Based Advanced Filters

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1033]
Child task of #175 
Blocked by #1027 

When the Date Advanced filter is available, this task involves adding the date specific advanced filter configs to the Customers report:

![image](https://user-images.githubusercontent.com/22080/49668325-96bb1b00-fa12-11e8-9aad-e7561e91560c.png)

**Comment by psealock** [comment]
https://github.com/woocommerce/wc-admin/pull/1305 closes this one
