### ISSUE TITLE
Product Report: Add filter by single category

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#1046]
~Determine if the~ Product Report should be filterable by a "Single Category" much like it currently is filterable by "Single Product".

### Why?

It would be nice to link the products count from the Categories table to the Products Report and look at only products of that category.

**Comment by timmyc** [comment]
@LevinMedia thoughts on this one?

**Comment by LevinMedia** [comment]
Humm, that's an interesting idea. I think we should add that to the backlog. You could also cross link from the category report by clicking on a category title in the tabular data.

**Comment by timmyc** [comment]
Looks like we have REST API support for the single category filter, so I'm going to add this to the sprint 👍

**Comment by psealock** [comment]
Related to https://github.com/woocommerce/wc-admin/issues/1277
