### ISSUE TITLE
Blank screen in IE11

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1062]
Last versions of `wc-admin` seem to be broken in IE11:

![image](https://user-images.githubusercontent.com/3616980/49806220-70211b00-fd57-11e8-976f-6281aded2228.png)

`<div id="root">`, which should contain the pages markup, is empty. There are no JS errors in the Console nor Network failures.

(Tested with BrowserStack)

**Comment by joshuatf** [comment]
Spent a while trying to debug this and did not get very far.  What I learned was:

* We have this bug going back as far as 8b963418c25456c6a4448c132ef1ec11f115086b
* 8b963418c25456c6a4448c132ef1ec11f115086b upgraded to buble v0.19.6 from v0.19.4.  Downgrading to v0.19.4 in master does not solve the issue.
* There seems to be intermittent errors that show up on some pages.  The arrow function used in `reducer()` inside d3-array/src/cross.js is the source of this error.

There seems to be something wrong with the es2015 transformations as far as I can tell.
