### ISSUE TITLE
Block: Stat Table

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#108]
From the latest design iteration ( p6riRB-3en-p2 ), one of the blocks still featured is a tabular list of "Top Selling Products":

![block-stat-table](https://user-images.githubusercontent.com/22080/41262862-364c3f30-6d98-11e8-8d6e-6a5f7958c9f1.png)

In lieu of creating a set of components that is specifically setup for Top Selling Products, I'm think we should make an abstract "Stat Table" set of components that will allow us or any extension developers to build display any form of data in a Block in a table. I also think we could leverage #92 when built for the table itself, and just modify styling for usage in the Overview/Dashboard area.

**Comment by timmyc** [comment]
The remaining item on this issue is to hook up the component to the new wp.data store:

* https://github.com/woocommerce/wc-admin/tree/master/client/store/reports/stats
* One good way to get to know how to use `wp.data` would be to give @justinshreve's [revenue report pr](https://github.com/woocommerce/wc-admin/pull/316) a review
* [The Gutenberg docs](https://github.com/WordPress/gutenberg/tree/master/packages/core-data) are also handy to have when first diving into using the core data packages too
* [The products stats endpoint](https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats) will be the data source for this component. It returns the product ID's currently, so we also will need to consider how to best grab that data. #295 has the beginnings of a data store for products. But there has also been discussion with @peterfabian about returning a limited product data set in the respond from the products stats endpoint to simplify things. For now we can continue to just show the product ID until we determine if the data can be returned in the same API request.
* TODO: we still need some designs around what to show here when no records are found, i.e. if no products have been sold /cc @jameskoster - for now we could stick with an empty table

**Comment by timmyc** [comment]
Thanks for the input @jameskoster - so for this particular component, do we want to have a min-height / fixed height, or are we okay with the block/component shrinking down when no data is present?

**Comment by jameskoster** [comment]
I think we could display a message. Something like;

![no sales](https://cldup.com/3qP4bsTKrz-2000x2000.png)

**Comment by timmyc** [comment]
Noting creation of a few follow-up issues that we can tackle when working on more dashboard blocks:

- Creation of EmptyCard #404
- Creation of EmptyTable #405

**Comment by Aljullu** [comment]
I just remembered we are still missing an error message for the Top Selling Products table when loading fails (https://github.com/woocommerce/wc-admin/blob/master/client/dashboard/top-selling-products/index.js#L93)

Should we create a follow-up issue @timmyc?

**Comment by timmyc** [comment]
Sure that would be great - do you want to create the issue @Aljullu ?

**Comment by Aljullu** [comment]
Done! #414
