### ISSUE TITLE
Honor WooCommerce Settings When Formatting Currency/Price

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/wc-admin#1090]
**Is your feature request related to a problem? Please describe.**

The current `formatCurrency()` function uses the store locale, but not the specific currency formatting options like "currency position". While it's unlikely that these will differ, it is possible.

> I think there could be some confusion about site language controlling the position/formatting of the symbol and separators rather than the WooCommerce > Settings > Currency Options. Could we roll our own format function that is a js version of `wc_price`/`get_woocommerce_price_format`?
> -- @justinshreve https://github.com/woocommerce/wc-admin/pull/122#pullrequestreview-130841773

**Describe the solution you'd like**

Use the WooCommerce Currency settings when formatting price values in JavaScript.

**Should this be prioritized? Why?**

Yeah, @timmyc saw this as the next step:

> I say we get this merged in so we at least have some proper currency formatting in place, and make an issue to possibly try using WC currency settings down the road.
> -- @timmyc https://github.com/woocommerce/wc-admin/pull/122#pullrequestreview-131807939

**Comment by timmyc** [comment]
We should probably make sure `<TextControlWithAffixes />` responds well to the currency position setting too.

**Comment by jeffstieler** [comment]
> We should probably make sure `<TextControlWithAffixes />` responds well to the currency position setting too.

`TextControlWithAffixes` doesn't know anything about currency, but `NumberFilter` does 😄 - https://github.com/woocommerce/wc-admin/pull/1089/files#diff-f8793909818544bf3db55597ce57543aR67
