### ISSUE TITLE
Feature Sweep: Report Template

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1098]
The feature sweep task involves revisiting a developed feature, and analyzing the components and functionality to ensure they match up with the original designed experience. Ideally you should perform a Feature Sweep using a device and/or browser that you typically do not work with. Try Browser Stack, or an emulator, try to feel experience through a different lens.

Prior to opening up additional issues, lets use this issue to discuss and log findings of your sweep - please share your browser/device config with your findings too.

**Comment by LevinMedia** [comment]
**enhancement**

At very large viewport sizes, the date range picker drop down and filter drop downs get stretched to infinity and beyond. To reduce the stretch effect, we should switch 1/4 width columns at viewport sizes of 1440 and larger:

<img width="1502" alt="screen shot 2018-12-14 at 4 56 32 pm" src="https://user-images.githubusercontent.com/4500952/50036895-6ef32680-ffc1-11e8-96c3-336db38beefb.png">

---

**enhancement**

Reduce the top and bottom margin around the filters on mobile (16px)

before:
<img width="447" alt="screen shot 2018-12-14 at 5 03 52 pm" src="https://user-images.githubusercontent.com/4500952/50037026-68b17a00-ffc2-11e8-9e5f-24ca6d4d6f3b.png">

After:
<img width="449" alt="screen shot 2018-12-14 at 5 03 41 pm" src="https://user-images.githubusercontent.com/4500952/50037030-71a24b80-ffc2-11e8-9786-8ec6cf06f6ec.png">

**Comment by timmyc** [comment]
Great catches here, thanks @LevinMedia

**Comment by timmyc** [comment]
I think this one belongs here, as I'm guessing it could happen in other filters:

Bug: Very long product names cause filter block to grow horizontally

![image](https://user-images.githubusercontent.com/22080/50309874-3afe8200-0455-11e9-99ab-2bbef91d6bdd.png)

**Comment by timmyc** [comment]
Opened up issues for all of the above, opted to not fix the long product name one for now as the more I look at it, it doesn't look that bad, and is kind of an edge case.
