### ISSUE TITLE
Feature Sweep: Chart Component

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1100]
The feature sweep task involves revisiting a developed feature, and analyzing the components and functionality to ensure they match up with the original designed experience. Ideally you should perform a Feature Sweep using a device and/or browser that you typically do not work with. Try Browser Stack, or an emulator, try to feel experience through a different lens.

Prior to opening up additional issues, lets use this issue to discuss and log findings of your sweep - please share your browser/device config with your findings too.

**Comment by LevinMedia** [comment]
**Bug / enhancement**

Single days and hourly intervals: When the selected date range is a single day, (ie: a single day picked from the custom date range picker, "today", or "yesterday" in the presets) the default interval should be "Hours"

When viewing an entire day with hourly intervals, the x-axis ticks should start at 12am and end at 11pm. 

When the time frame is today's date, and set to hourly intervals, the graph only plots up to and including the current hour of the day. 

When viewing single day time frames the secondary X axis should always include the month, day and year. 

<img width="975" alt="screen shot 2018-12-14 at 10 05 45 pm" src="https://user-images.githubusercontent.com/4500952/50039772-ac20de00-ffec-11e8-88c6-03971b28fe09.png">

---

**bug / enhancement** 

Update the intervals available for different date ranges as follows:

**Date range:** 1 day **Intervals:** hours, days
**Date range:** 2 - 6 days **Intervals**: Days
**Date range:** >= 7 days **Intervals**: Days, Weeks
**Date range:** >= 28 days **Intervals**: Days, Weeks, Months
**Date range:** >= 90 days **Intervals**: Days, Weeks, Months, Quarters
**Date range:** >= 365 days **Intervals**: Days, Weeks, Months, Quarters, Years

---

**Enhancement** 

When viewing a single day, with the interval set to day, and the chart set to line chart - center the points in the graph

<img width="1641" alt="screen shot 2018-12-14 at 10 32 19 pm" src="https://user-images.githubusercontent.com/4500952/50039944-26069680-fff0-11e8-937a-4962e1f64a8b.png">

---

**Enhancement** 

Remove unnecessary decimal points from Y-axis ticks

before:
<img width="459" alt="screen shot 2018-12-14 at 10 57 09 pm" src="https://user-images.githubusercontent.com/4500952/50040186-9cf15e80-fff3-11e8-8c03-d09683f7e7b8.png">

After:
<img width="463" alt="screen shot 2018-12-14 at 10 56 00 pm" src="https://user-images.githubusercontent.com/4500952/50040192-aa0e4d80-fff3-11e8-8604-4dc1440d0ad6.png">


---

**bug** 

The width of the charted area changes when toggling between line and bar chart. 

![screen recording 2018-12-14 at 10 39 pm](https://user-images.githubusercontent.com/4500952/50040121-5c451580-fff2-11e8-936b-bd55cd5b95c8.gif)

Also for both line and bar charts in particular on smaller viewport, the maximum plotable area is not used. 

![screen-shot-2018-12-14-at-10 41 16-pm](https://user-images.githubusercontent.com/4500952/50040182-8ba85200-fff3-11e8-8943-cf5ee72ec776.jpg)


---

**bug**

Can not plot more than 88 days in bar chart mode on mobile viewports (<=375px wide)

<=88 days:

<img width="405" alt="screen shot 2018-12-14 at 11 10 52 pm" src="https://user-images.githubusercontent.com/4500952/50040302-96fc7d00-fff5-11e8-986b-a346252d0a86.png">


>=89 days:

<img width="421" alt="screen shot 2018-12-14 at 11 10 38 pm" src="https://user-images.githubusercontent.com/4500952/50040312-c8754880-fff5-11e8-93b1-25de1ed760f3.png">

This problem exists at other viewport / date range combinations and it likely has to do with the number of bars we're trying to render in such a small space. We'll likely have to find some kind of broad solution to address

**Bug**

When the only data to graph has a value of 1, the y-axis ticks count: 1, 1, 2

<img width="1099" alt="screen shot 2018-12-14 at 11 16 37 pm" src="https://user-images.githubusercontent.com/4500952/50040343-8b5d8600-fff6-11e8-83a4-5bd90390100a.png">

they should count 1, 2, 3, and the bar / line should only extend to the first y-axis tick.

**Comment by timmyc** [comment]
**Bug:**

Y-axis ticks when quantity one is only shown results in odd behavior:

![products analytics woo test woocommerce 2018-12-20 12-42-57](https://user-images.githubusercontent.com/22080/50310332-8d8c6e00-0456-11e9-9cba-2327ba3ff6f2.png)

**Comment by timmyc** [comment]
**Bug:**
Round number ( 2 in this case ) not plotted along the appropriate y-axis line:

![products analytics woo test woocommerce 2018-12-20 12-42-03](https://user-images.githubusercontent.com/22080/50310374-a8f77900-0456-11e9-9c72-76bce79bea99.png)

**Comment by LevinMedia** [comment]
**Bug / enhancement**

Single days and hourly intervals: When the selected date range is a single day, (ie: a single day picked from the custom date range picker, "today", or "yesterday" in the presets) the default interval should be "Hours"

When viewing an entire day with hourly intervals, the x-axis ticks should start at 12am and end at 11pm. 

When the time frame is today's date, and set to hourly intervals, the graph only plots up to and including the current hour of the day. 

When viewing single day time frames the secondary X axis should always include the month, day and year. 

<img width="975" alt="screen shot 2018-12-14 at 10 05 45 pm" src="https://user-images.githubusercontent.com/4500952/50039772-ac20de00-ffec-11e8-88c6-03971b28fe09.png">

**Comment by LevinMedia** [comment]
**bug / enhancement** 

Update the intervals available for different date ranges as follows:

**Date range:** 1 day **Intervals:** hours, days
**Date range:** 2 - 6 days **Intervals**: Days
**Date range:** >= 7 days **Intervals**: Days, Weeks
**Date range:** >= 28 days **Intervals**: Days, Weeks, Months
**Date range:** >= 90 days **Intervals**: Days, Weeks, Months, Quarters
**Date range:** >= 365 days **Intervals**: Days, Weeks, Months, Quarters, Years

**Comment by LevinMedia** [comment]
**Enhancement** 

When viewing a single day, with the interval set to day, and the chart set to line chart - center the points in the graph

<img width="1641" alt="screen shot 2018-12-14 at 10 32 19 pm" src="https://user-images.githubusercontent.com/4500952/50039944-26069680-fff0-11e8-937a-4962e1f64a8b.png">

**Comment by LevinMedia** [comment]
**Enhancement** 

Remove unnecessary decimal points from Y-axis ticks

before:
<img width="459" alt="screen shot 2018-12-14 at 10 57 09 pm" src="https://user-images.githubusercontent.com/4500952/50040186-9cf15e80-fff3-11e8-8c03-d09683f7e7b8.png">

After:
<img width="463" alt="screen shot 2018-12-14 at 10 56 00 pm" src="https://user-images.githubusercontent.com/4500952/50040192-aa0e4d80-fff3-11e8-8604-4dc1440d0ad6.png">

**Comment by LevinMedia** [comment]
**bug** 

The width of the charted area changes when toggling between line and bar chart. 

![screen recording 2018-12-14 at 10 39 pm](https://user-images.githubusercontent.com/4500952/50040121-5c451580-fff2-11e8-936b-bd55cd5b95c8.gif)

Also for both line and bar charts in particular on smaller viewport, the maximum plotable area is not used. 

![screen-shot-2018-12-14-at-10 41 16-pm](https://user-images.githubusercontent.com/4500952/50040182-8ba85200-fff3-11e8-8943-cf5ee72ec776.jpg)

**Comment by LevinMedia** [comment]
**bug**

Can not plot more than 88 days in bar chart mode on mobile viewports (<=375px wide)

<=88 days:

<img width="405" alt="screen shot 2018-12-14 at 11 10 52 pm" src="https://user-images.githubusercontent.com/4500952/50040302-96fc7d00-fff5-11e8-986b-a346252d0a86.png">


>=89 days:

<img width="421" alt="screen shot 2018-12-14 at 11 10 38 pm" src="https://user-images.githubusercontent.com/4500952/50040312-c8754880-fff5-11e8-93b1-25de1ed760f3.png">

This problem exists at other viewport / date range combinations and it likely has to do with the number of bars we're trying to render in such a small space. We'll likely have to find some kind of broad solution to address

**Comment by LevinMedia** [comment]
**Bug**

When the only data to graph has a value of 1, the y-axis ticks count: 1, 1, 2

<img width="1099" alt="screen shot 2018-12-14 at 11 16 37 pm" src="https://user-images.githubusercontent.com/4500952/50040343-8b5d8600-fff6-11e8-83a4-5bd90390100a.png">

they should count 1, 2, 3, and the bar / line should only extend to the first y-axis tick.

**Comment by LevinMedia** [comment]
**Enhancement**

Add spinner to empty chart while data is loading

<img width="1574" alt="screen shot 2018-12-19 at 8 43 56 pm" src="https://user-images.githubusercontent.com/4500952/50264314-e0bade00-03ce-11e9-9aa1-0a82aa6455ee.png">

**Comment by timmyc** [comment]
I have created issues for all of the above so closing this one out.
