### ISSUE TITLE
Category sorting by name doesn't work in categories report

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1111]
**Describe the bug**
On the Category report page, clicking the "Category" column does not sort correctly.

Blocked by #996 and #1110.

**To Reproduce**

1. Go to the category report page.
2. Click "Category"
3.  Note the lack of sorting

**Expected behavior**
Expected to click "Category" and rows to be sorted alphabetically by category name.

**Comment by justinshreve** [comment]
@psealock Are you still looking at this one? It looks like you have a few tasks assigned to you around filters and I'm already doing some REST API work this week so I'm happy to take a look at this one.

**Comment by justinshreve** [comment]
I just noticed on our P2 that you are AFK this week -- so I'll go ahead and grab this one.
