### ISSUE TITLE
Number filter values should be set in state

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1115]
**Describe the bug**
Values for inputs should be set in state.  Currently this error is shown when a number filter is used:
`A component is changing an uncontrolled input of type number to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

**To Reproduce**
1.  Visit the devdocs.
2. Add the subtotal filter under the "Advanced Filters."
3. Add and remove a value in the input field.
4. Note the error in the console.

**Expected behavior**
Expected no error to occur.

**Screenshots**
<img width="623" alt="screen shot 2018-12-18 at 6 09 10 pm" src="https://user-images.githubusercontent.com/10561050/50147156-63b93700-02f0-11e9-8521-14f95f2c55ed.png">

**Comment by jeffstieler** [comment]
I can't seem to reproduce this - I've tried Chrome, Safari, and Firefox. Is there any additional information you can provide, or perhaps can someone else reproduce this?
