### ISSUE TITLE
Design issue : For header icon menu tray

### ISSUE THREAD

**Issue by ronakganatra9** [woocommerce/wc-admin#1130]
**Describe the bug**
In the Header right-hand side Menu icon tray, there is a minor design issue which I found while testing it.
Hover and click time bug.

**To Reproduce**

1. Go to 'WooCommerce Dashboard'
2. Click on 'Stock' from right-hand side menu tray
3. Again click on  'stock' the panel will be hidden but the stock background color will not be removed it will stay there.

**Expected behavior**
When we click on stock and the panel will display at that time stock button background color should stay it is correct but when we click again on the stock button and the panel will be hidden at that time stock button background color should be removed.

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24435113/50205012-ceb84b80-038c-11e9-8bbf-4e845fefa7b5.gif)

**Desktop (please complete the following information):**

* OS: Ubuntu 18.04
* Browser Chrome
* Version latest

**Comment by timmyc** [comment]
@ronakganatra9 thank you much for the bug report. Confirmed the same thing is happening in Chrome.

**Comment by LevinMedia** [comment]
@ronakganatra9 - I'm seeing the same thing too. The focused state has the same background style as the selected state so it's confusing. I'll bring focus styles of the activity panel buttons inline with the summary numbers to smooth it out.

**Comment by LevinMedia** [comment]
@Aljullu Affirmative. In the case where it's selected + focused, it would keep the purple highlight at the bottom as well.
