### ISSUE TITLE
I cant see orders after plugin activation

### ISSUE THREAD

**Issue by ghanchi2000** [woocommerce/wc-admin#1139]
After i activated plugin.
I cant see "All Orders" in order page
I can See "Mine" Section of order page
After click Processing on order page then i see order listed

Why this plugin change database of orders and woocommerce ? it should create their own database if needed I have over 15000 orders and i cant see any thing there

after disabling plugin i cant see orders also

**Comment by willgorham** [comment]
This is probably related to WC core and not this plugin specifically: https://github.com/woocommerce/woocommerce/issues/22271

**Comment by timmyc** [comment]
Thanks for reaching out @ghanchi2000 - indeed it sounds like the bug you experienced was a result of the issue @willgorham linked to above. There was a 3.5.3 release of WooCommerce yesterday that fixes the problem.

This plugin doesn't modify any of the order table data - or the functionality of processing orders ( listing / editing / etc ).

I will however mention that the process this plugin takes to populate the order lookup tables might not work flawlessly on 15000 orders - we are actively still optimizing this part of the code. I'd love to get in touch with you when this work has been completed though and see how it works on your test site with 15k orders if you don't mind.
