### ISSUE TITLE
Component: Store Alerts (aka Priority Notices)

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#115]
While the Sidebar/Activity panel boasts a new "Inbox" to communicate key items to users - the latest [Dashboard Design](https://sketch.cloud/s/rQMvE/all/prototype/dashboard/play) displays the new Store Alert section where critical/show stopper alerts will be displayed to users:

<img width="1009" alt="storenotices" src="https://user-images.githubusercontent.com/22080/41384870-299fe4f8-6f2d-11e8-9ba5-1519a3e50a63.png">

While I believe we still need some more in-depth designs to fully vet the functionality and display of these Store Alerts, I think we can begin on building the basic component that they will call home.

__Features__
- Store Alerts should be able to consume an array alerts, or possibly child components ( up to the implementor )
- An individual alert currently appears to support a severity gridicon, a title, content, a call to action button, and the ability to "snooze" the alert.
- Arrows in the upper right corner allow users to toggle between the alerts in the panel.

__Design Questions__
- Will there be differing severity levels for the alerts? If so what are they and the corresponding icons and colors for the left border.
- Will any alerts have more than one action button?
- When the final alert has been acted upon, will we display a success message, or simply collapse the panel from view?

/cc @jameskoster

**Comment by allendav** [comment]
@LevinMedia - is there a mock that shows how this should integrate within a page? And what pages should this appear on (e.g. WooCommerce and Analytics pages only, or Dashboard and Analytics only, etc)

**Comment by LevinMedia** [comment]
@allendav when WC admin as active,  this notification should appear on all WC pages just below the activity bar

<img width="1281" alt="screen shot 2018-11-15 at 1 08 04 pm" src="https://user-images.githubusercontent.com/4500952/48581850-d2f9d080-e8d7-11e8-8320-e46adc8fc87b.png">

Invision Inspect:
https://automattic.invisionapp.com/d/main#/console/15991553/331680393/inspect
