### ISSUE TITLE
Dashboard: Create Top Categories Block

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1192]
This task involves creating a new "Top Categories" Block for the dashboard leaderboard section:

![image](https://user-images.githubusercontent.com/22080/50460231-1446bc80-0929-11e9-8585-f9a354689e73.png)

The table should show the categories with the most items sold:

Category|Items Sold|G. Revenue
---------|-----------|-----------
Category Name linked Product Listing|# of Products sold from category in period|Revenue of Products sold

@LevinMedia should we link the category name to the product listing for that category `/wp-admin/edit.php?s&post_status=all&post_type=product&action=-1&product_cat=CATEGORY-NAME`

**Comment by LevinMedia** [comment]
@timmyc once filtering lands in the tabular data, it should link to the category report, filtered by the category name. 

<img width="830" alt="screen shot 2018-12-27 at 8 36 46 am" src="https://user-images.githubusercontent.com/4500952/50487323-afd03f80-09b2-11e9-8ad6-26972aa2bfe9.png">
