### ISSUE TITLE
Date: Unit Tests fail 11pm UTC

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#1218]
**Describe the bug**
Unit tests fail at 11pm UTC on Travis for one hour. 

**To Reproduce**
I haven't tried, but I believe you can replicate locally by running unit tests at 11pm local time.

**Cause**

`getCurrentPeriod` adds one hour to `primaryEnd`, which is the next day at 11pm.

https://github.com/woocommerce/wc-admin/blob/8494e21bfa7f5463106c4c47c95e6b79396d6b86/packages/date/src/index.js#L175

**Additional context**

We can easily fix the unit tests to accomodate this, however, some investigation might reveal a problem with the UI when viewing reports late at night.

**Comment by Aljullu** [comment]
I can take a look at this since it looks like I introduced this bug. :+1:
