### ISSUE TITLE
Settings page creation and excluded statuses

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1252]
A "Settings" page is needed to store global settings for reporting.  Initially this will involve:
* Creating the settings page.
* Creating the "Excluded Statuses" settings.
* Storing these settings in `wcSettings`.
* Hooking up saved settings to the excluded statuses array in #1251 

<img width="1049" alt="screen shot 2019-01-08 at 3 45 38 pm" src="https://user-images.githubusercontent.com/10561050/50817155-ef593d00-135d-11e9-961f-e6ffc0155b9e.png">

Before starting on this task, check with @LevinMedia for the final design on this page.

**Comment by timmyc** [comment]
From @LevinMedia:

We should also allow users to configure some per-user defaults on this page for date range and interval - I.E. perhaps my preference is to view the last quarter of data, compared to the prior year, and the charts be set to a weekly interval.

**Comment by LevinMedia** [comment]
Sure is
