### ISSUE TITLE
Gross revenue summary number is broken in Categories report

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1254]
The _Gross revenue_ number in the _Categories_ report is broken:

![image](https://user-images.githubusercontent.com/3616980/50829449-df812f00-1344-11e9-9b2b-e76a7bd43c6b.png)

The issue is that we are trying to render the value `net_revenue` but the API provides us `gross_revenue`.

**Comment by peterfabian** [comment]
Swaggerhub updated.
