### ISSUE TITLE
Registered users do not return a customer ID

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1263]
**Describe the bug**
#1144 added in a customers data store that tracks stats for both guests and registered customers 🎉

This should create unique customer IDs for all guest and regular customers in the `wc_customers_lookup` table.  Some orders in the `wc_orders_stats` table appear to have a `customer_id` of `0`.

These orders at first glance appear to be associated with already created accounts, so it looks like customer IDs may be bypassed when users are not created directly through WooCommerce (e.g., admins, manual user creation, or other sign-up forms).

This blocks conditions don't pass and a number is not returned:
https://github.com/woocommerce/wc-admin/blob/36a6b53aa262c25b5e2c4c1730b55e3bf0311bcf/includes/data-stores/class-wc-admin-reports-orders-data-store.php#L495-L498

It's possible that the user creation never passed by any of these hooks:
https://github.com/woocommerce/wc-admin/blob/36a6b53aa262c25b5e2c4c1730b55e3bf0311bcf/includes/data-stores/class-wc-admin-reports-customers-data-store.php#L71-L74

**To Reproduce**
1.  Create orders programmatically or rebuild all orders that were associated with an admin account.
2.  Note the `customer_id` is not created for those accounts and associated orders have a `customer_id` of `0`.

**Expected behavior**
Expected a `customer_id` associated with this account and respective orders.

**Screenshots**
<img width="802" alt="screen shot 2019-01-09 at 4 14 24 pm" src="https://user-images.githubusercontent.com/10561050/50885789-ad95c880-1429-11e9-8e46-ea6757218a48.png">

**Comment by jeffstieler** [comment]
@timmyc @joshuatf I'm unable to reproduce this - I have 3 orders associated with my admin account (user #1) and the rows in the order stats table do have a `customer_id`. Can you elaborate a bit on your instructions to reproduce?

**Comment by joshuatf** [comment]
@jeffstieler Sure!  Here are a couple places where this problem exists:

### Guests without emails

This may be a corner case, but I think smooth generator has created a few orders without email addresses.  If there's no email, the customer isn't stored.  I see 2 options for this:
1. Continue not storing these users.  I think this option is *okay* provided we set the `customer_id` to `NULL` in `wc_order_stats`.
2. Store them without an email.  Obviously these customers can only be attached to that one order without the option to attach to existing future orders, but this data may be useful for stats at some point.

I'm leaning towards the 2nd option here, but let me know what you think.

### Programmatic or existing users
This one is a little bit trickier to reproduce, but the easiest way is to dump the customers and orders stats table from the tests in `/tests/reports/class-wc-tests-reports-orders.php`.  You'll notice that customers haven't been created and `customer_id` will be `0` for each of the order stats.

This problem is also present in users who do not hit one of the hooks (`woocommerce_new_customer`, `woocommerce_update_customer`, `edit_user_profile_update`, `updated_user_meta `).  This can happen when:
* A user already existed prior to plugin activation.
* Users are imported.
* Users are created in the admin panel.
* Users are created through non-WC forms.
* Users are created programmatically (e.g., `WC_Helper_Customer::create_customer()`).

This means the customer is not present in the `wc_customers_lookup` table when the order hook is triggered.  An easy solution for this might be to swap out the function here:
https://github.com/woocommerce/wc-admin/blob/36a6b53aa262c25b5e2c4c1730b55e3bf0311bcf/includes/data-stores/class-wc-admin-reports-orders-data-store.php#L493
with a similar method to the one we use for guests:
`get_or_create_customer_by_user_id()`

**Comment by jeffstieler** [comment]
The hook problem seems to be caused by a poor choice of initial hook - `'wp'`. I changed that to `'wp_loaded'` here: https://github.com/woocommerce/wc-admin/pull/1180/commits/1e7b673512e0e9ab636068d4241ec5e61245a96d

Let's continue the discussion over on that PR.

**Comment by joshuatf** [comment]
@jeffstieler Nice solution.  I think that resolves all the existing user issues.  Any thoughts on guests without emails?

**Comment by jeffstieler** [comment]
@joshuatf - I believe the "guests without emails" scenario to definitely be an edge/corner case. Considering we're using billing email to identify guest customers, I think we should go with option #1 you've listed above (not storing them).

_cc: @timmyc as this seems to be an important decision_

**Comment by timmyc** [comment]
I'm fine with option one too, definitely feels like an edge case to me - seems like the only scenario would be when manually creating an order where this would be hit correct?

**Comment by jeffstieler** [comment]
> seems like the only scenario would be when manually creating an order where this would be hit correct?

Yep, unless the store filtered the required fields at checkout to no longer require email.. but that seems unlikely for an online store to do..

**Comment by jeffstieler** [comment]
@timmyc @joshuatf can this be closed?
