### ISSUE TITLE
Package `react-world-flags` is inflating file sizes

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#1275]
I noticed this in the blocks plugin, since we're using `@woocommerce/components`, we import the very large library `react-world-flags`. I'm working on splitting out node_module files int a vendors file, and with that, I can profile the bundles and see that this package alone is 4.3MB (moment-timezone being the next largest single package at 929KB).

<img width="965" alt="screen shot 2019-01-10 at 3 11 56 pm" src="https://user-images.githubusercontent.com/541093/50994404-34aa7580-14ea-11e9-8f5d-63b9bc07844a.png">

I can run the same thing on this project and we see the same thing, react-world-flags is a significant part of each file. 

<img width="1306" alt="screen shot 2019-01-10 at 3 15 56 pm" src="https://user-images.githubusercontent.com/541093/50994599-b26e8100-14ea-11e9-876e-51f6aafa20a2.png">

To generate this yourself, you can run:

```
npx webpack --profile --json > wc-admin-stats.json
npx webpack-bundle-analyzer wc-admin-stats.json
```

I'm not sure if the solution is to find a different package, explore splitting it out, some kind of lazy-loading scenario, or ... something else, but it would be good to investigate.

**Comment by timmyc** [comment]
yikes! wonder if we should implement an emoji-flag instead - like https://github.com/matiassingers/emoji-flags - @LevinMedia any thoughts on this? I think the only place we are actually showing the flag is on the country advanced filter - we don't even show the country flag in the customers table content.

**Comment by psealock** [comment]
I played around with emoji-flags (linked above) and it shaves a nice 4.2MB from the app 🎉 .

However, core replaces the emoji with an `<img />` which adds a request for an image. I'm not entirely sure why that should happen since my browser has emoji support. Even so, this seems the way to go instead of shipping 4.3MB with wc-admin.

**Comment by timmyc** [comment]
> However, core replaces the emoji with an <img />

Wow interesting, so WordPress core is doing that? Even in the context of rendering it via React?!

**Comment by psealock** [comment]
Yes! It uses a MutationObserver to check nodes added dynamically to the page and parses `textContent` to see if it contains an emoji. Its supposed to be a fallback for browsers that don't support emoji, but its not working well. Here is the culprit:

https://github.com/WordPress/WordPress/blob/24e8467c6f82bdf02da032095dc35fb7dde877fd/wp-includes/js/wp-emoji-loader.js#L40-L54

The resulting `_wpemojiSettings.supports.emoji` is false for me in Chrome, FF, and Safari.

**Comment by timmyc** [comment]
TIL - huh well I guess we should a ticket in trac about `_wpemojiSettings.supports.emoji` being invalid. I agree though that even with the img being loaded instead, going with the emoji-flags solution will reduce the bundle size which is the end goal.
