### ISSUE TITLE
Incorrect interval displayed in default report view (hours, should be days)

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1278]
**Describe the bug**
When viewing a report, the default interval is set to hour. 

**To Reproduce**
1. On master, navigate to a report (ie: revenue)
2. note the interval is set to "hours"

**Expected behavior**
The interval should be set to day, and hours should only be available as an interval when viewing a single day. 

**Screenshots**
<img width="3012" alt="screen shot 2019-01-10 at 3 42 29 pm" src="https://user-images.githubusercontent.com/4500952/51004234-9d93ec80-14ee-11e9-8835-58c0fa5b4832.png">

**Comment by timmyc** [comment]
Was just about to report this too as I hit it while testing #1273. On the dashboard I currently have month to date set in the date picker, and noticed my laptop fan was going crazy - opened up the network tab and saw:

![dashboard-with-six-charts-enabled](https://user-images.githubusercontent.com/22080/51005742-e6e73a80-14f4-11e9-8d55-0f878bf5b45d.png)

I have six charts enabled and you can see the first 12 requests ( yes we might want to consider the heavy-ness of the dashboard charts ) for the initial load, and then the requests or pages 2 and 3 from the same endpoints for both date periods - 😱
