### ISSUE TITLE
Analytics: Product Detail Report Summary Numbers Invalid 

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1292]
When viewing a product detail report, for a product that has variations sold within a selected period, the table summary numbers are not being calculated correctly:

![image](https://user-images.githubusercontent.com/22080/51063147-9207fa80-15ae-11e9-95ec-47280d26f771.png)

__Steps to Reproduce__
- Create a product with variations
- Place a test order
- View the Products Detail Report for that product, note the summary numbers are zero.

**Comment by justinshreve** [comment]
I started looking at this, and feel it will be handled as a part of #564 which I just took over. Closing this since it will be handled over there.
