### ISSUE TITLE
Analytics: Customers Report Endless Loop

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1304]
When viewing the customers report, and accessing a new page of data - there appears to be an endless loop that continually requests the same API resource every few seconds.

**To Reproduce**

1. Your database must have at least 75 customers to have a paged data set. I'm using a woocommerce.com backup that has over 6k customers
2. Open your network console, and load the customers report. Click on the pagination link to load up another page of data

This is a very boring .gif of the loop in action:

My endless loop file is too large :) - I will reproduce and post it later today.

**Comment by timmyc** [comment]
Indeed verified `isShallowEqual()` is returning falsey on the two identical objects - wondering if due to the nested deep/nature of these objects, we can't expect it to work here. This example code in any wc-admin console will reproduce the issue:

```
const test1 = {
  "primaryData": {},
  "tableData": {
    "query": {
      "orderby": "date_registered",
      "order": "desc",
      "after": "2019-01-01T00:00:00+00:00",
      "before": "2019-01-16T23:59:59+00:00",
      "page": "7",
      "per_page": 25
    },
    "isRequesting": true,
    "isError": false,
    "items": {
      "data": []
    }
  },
  "userPrefColumns": ""
};

const test2 = {
  "primaryData": {},
  "tableData": {
    "query": {
      "orderby": "date_registered",
      "order": "desc",
      "after": "2019-01-01T00:00:00+00:00",
      "before": "2019-01-16T23:59:59+00:00",
      "page": "7",
      "per_page": 25
    },
    "isRequesting": true,
    "isError": false,
    "items": {
      "data": []
    }
  },
  "userPrefColumns": ""
};

wp.isShallowEqual( test1, test2 );
```

**Comment by timmyc** [comment]
I also just now tried using lodash.isEqual to test things out - still seeing continuous requests as described in the initial report above in Firefox

**Comment by jeffstieler** [comment]
From what I can tell this has something to do with the `timeout` value and fresh-data. If I increase the timeout to 15-20s and the request comes back within that time, no extra requests are issued. If the request doesn't respond within the `timeout` window, another is issued.

Upping the `timeout` might fix the symptoms, but is a band aid, not a real fix.

_cc: @coderkevin again for ideas - I'll continue digging into fresh-data_

**Comment by timmyc** [comment]
Thanks for checking it out Jeff, definitely jives with what I was seeing too. I think upping the timeout is fine - but also feels like it is a bug in fresh-data as if a request is still resolving for the same resource/query args, it should not issue another request.

**Comment by jeffstieler** [comment]
I'll stick to upping the timeout in `wc-admin` to help alleviate this issue for now - the changes that will need to be made to `fresh-data` don't have a clear path forward. (Do we add exponential backoffs? Should the "read" operation callbacks be able to determine if there's a request in flight? Etc..)
