### ISSUE TITLE
Tests fail when started at the end of the hour

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1316]
**Describe the bug**
When starting tests at the end of the hour (e.g. 10:59), they sometimes seem to fail.  I suspect that this has to do with the `before` and `after` query parameters used for the data store in 

**To Reproduce**

1. Start unit tests at the end of the hour (or replicate this by modifying system time).
2. Unit tests should complete after the hour is over.
3. Note the failed tests.

**Expected behavior**
Expected tests to not fail.

**Additional context**
Occurred in this issue - https://github.com/woocommerce/wc-admin/pull/1180

**Comment by psealock** [comment]
Are you modifying system time in Preferences in mac?

![screen shot 2019-01-17 at 11 59 18 am](https://user-images.githubusercontent.com/1922453/51283786-28746a00-1a4e-11e9-9d2a-7074384a2b17.png)

I can't replicate, but I'll try some more.

**Comment by psealock** [comment]
Whoops I was just looking at client side tests. I think this is it

![screen shot 2019-01-17 at 2 33 44 pm](https://user-images.githubusercontent.com/1922453/51289451-1eaa3100-1a65-11e9-9441-4dcf6ed79dd7.png)

**Comment by joshuatf** [comment]
@psealock That's it!  Sorry, I should have specified phpunit tests.

I seem to recall more errors happening around this related to total order count and value since the `before` and `after` query params were slightly off (I did not screenshot unfortunately), but maybe they will pop up once that initial error is fixed.

**Comment by justinshreve** [comment]
I'm able to reproduce getting different parts of the same test to fail at the top of the hour but I'm having trouble debugging it. I was wondering if anyone else had ideas from reproducing it? 

Some notes:

The test sets a lot of time variables and does some math on them so somewhere, something is not calculated correctly.

One such example:

```
$current_hour_minutes = (int) $current_hour->format( 'i' );
$current_hour->setTimestamp( $order_1_time - $current_hour_minutes * MINUTE_IN_SECONDS );
$now = new DateTime();
```

I was thinking maybe, when the clock rolls over, the $current_hour_minutes calculation does something unexpected -- but looking at the actual error --

```Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
-            'date_end' => '2019-01-18 20:00:28'
-            'date_end_gmt' => '2019-01-18 20:00:28'
+            'date_end' => '2019-01-18 19:59:59'
+            'date_end_gmt' => '2019-01-18 19:59:59'
```

It looks like the actual API response is capping out at the hour. So perhaps its an actual issue with the API?

The test alone is 3000 lines long (!!!) making it hard to debug.

@peterfabian Do you have some cycles to help look at this as the original author? You probably have a better understanding of some of the date/interval handling.

**Comment by peterfabian** [comment]
I'll have a look at this.

Side note: sorry, I know the test is bonkers, I wanted to create the order set covering possible values for coupons, customers, order statuses and products and run all test on the set created once instead of creating the order set for each assert, as it would take too much time.
