### ISSUE TITLE
Disabled 'Filter' button shouldn't change text color on hover

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1339]
- Go to the _Downloads_ report and select _Advanced Filters_ under the _Show_ dropdown (or directly go to `wc-admin#/analytics/downloads?filter=advanced`).
- Notice the _Filter_ button is disabled.
- Hover it.
- Notice the text color changes.

![button](https://user-images.githubusercontent.com/3616980/51314580-61add980-1a50-11e9-9537-e84ddb180ee3.gif)

Expected result:
- The text color should not change if the button is disabled.

@timmyc I added the _Good First Issue_ label here. Feel free to remove it if you think this is not a good issue for new contributors. :man_technologist:

**Comment by timmyc** [comment]
Great use of the label, thanks Albert
