### ISSUE TITLE
Add Feature Flags

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1345]
Since we are punting the activity panels feature until after 3.6, we need the concept of feature flags to disable the feature, but keep it around for the future. This also comes in handy so we can continue to use `wc-admin` to develop/build updates for core in the future.

I think we should support multiple environments (production, dev). The flags should also be available via PHP if possible (the activity panel contains PHP code as well).

Some prior art/related discussions:

* https://github.com/WordPress/gutenberg/issues/11016
* https://github.com/WordPress/gutenberg/issues/11016#issuecomment-447210849
* https://github.com/Automattic/wp-calypso/tree/master/config#feature-flags
* https://github.com/WordPress/gutenberg/pull/13324

**Comment by timmyc** [comment]
While this isn't as pressing of a need anymore, I still feel it could be useful for targeting the ecomm plans to roll out wc-admin.
