### ISSUE TITLE
Remove Activity Panel

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1346]
Blocked by #1345.

Prior to 3.6, we need to remove the activity panel from our current build. Using feature flags, we can keep the code around. This issue is considered finished when we can release a bundled .zip without the activity panel, breadcrumbs, and "embed" entry point code.

**Comment by timmyc** [comment]
Confirming that by Activity Panel we also are including the header area too?

![image](https://user-images.githubusercontent.com/22080/51409934-09daa580-1b18-11e9-96e9-0c3fdbfee41f.png)

Other question on this one, without the activity panels, I'm assuming we are no longer hiding admin alerts too.

 /cc @LevinMedia

**Comment by justinshreve** [comment]
> Confirming that by Activity Panel we also are including the header area too?

Yes - the breadcrumbs should be removed too. We can't accurately do them without smarter page handling: p90Yrv-U3-p2.

> Other question on this one, without the activity panels, I'm assuming we are no longer hiding admin alerts too.

Good question.
 
We could do a simple hide on the dashboard and reports (using CSS) like we do in the eCommerce plan, since users will still see notices in other sections of WooCommerce.

Or we could move the current logic out and have a different button for showing/hiding them? I'd hate to clutter up our reports and dashboard with a bunch of notices out of the box.

**Comment by justinshreve** [comment]
> but hiding notices and not providing an alternative way to access them on those screens might be dangerous.

What about just an indicator/button for WP notices like I mentioned above? Something like this (mocked up with Inspector -- the button/link can be something else):

<img width="955" alt="screen shot 2019-01-21 at 10 52 19 am" src="https://user-images.githubusercontent.com/689165/51488105-b1ebab00-1d72-11e9-96e4-6ff47c9b26d4.png">

<img width="954" alt="screen shot 2019-01-21 at 11 48 56 am" src="https://user-images.githubusercontent.com/689165/51488112-b7e18c00-1d72-11e9-845c-0ac028910dcf.png">

**Comment by josemarques** [comment]
@timmyc I believe it's no longer necessary to remove the Activity Panel due to re-planning of release cycles and keeping this as feature plugin?

**Comment by timmyc** [comment]
That is correct @josemarques I'll close this out.
