### ISSUE TITLE
REST API: Investigate Slow Customers Response

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1372]
Follow up from #1369 - where we increased the timeout in the `wc-api` layer to 60 seconds, the response from a default query of the customers page is quite slow, often taking over 30 seconds in my testing. With Query Manager enabled on my test site, for a first request for one page of customers data

`https://woocommerce.test/wp-json/wc/v4/reports/customers?after=2019-01-01T00:00:00+00:00&before=2019-01-22T23:59:59+00:00&order=desc&orderby=date_registered&page=6&per_page=25&_locale=user`

![image](https://user-images.githubusercontent.com/22080/51560404-44ef1880-1e39-11e9-9d34-f813c4426079.png)

I added the `XWP-TotaQueries` on the customers report response, which is always 44 queries regardless of cache being primed or not. The identical request on second load:

![image](https://user-images.githubusercontent.com/22080/51560514-8d0e3b00-1e39-11e9-96ce-8a2ac09f85f2.png)

/cc @jeffstieler

**Comment by jeffstieler** [comment]
I'm not sure there's much to do here after #1435.

It looks like all the tables have indexes for the `JOIN` columns so I don't think there are any quick wins on the query front.

I'm noticing a 3+ second TTFB for all requests that come through the browser. Chrome being the fastest, Firefox being about twice as slow. This TTFB delay is present for vanilla WP requests (HTML) as well as REST API requests.

**Comment by timmyc** [comment]
Were you saying that requests were generally faster in Postman too?

**Comment by jeffstieler** [comment]
> Were you saying that requests were generally faster in Postman too?

Yep, mainly because there wasn't such a long delay for TTFB.

**Comment by timmyc** [comment]
Slowness of the stack. Ugh. Well I'm fine with closing this out. For QA issues next release I'm looking to collect some data around response times of endpoints across the reports to see if we might still have some easy-optimizing to do in a few spots. Also feel testing against the wccom dataset might help uncover some of those with the exhausted memory error.

Thanks for digging in on this one further @jeffstieler - I'm good with closing this.
