### ISSUE TITLE
Packages: import of `lib/number` in currency package is breaking external builds

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#1390]
[In this commit,](https://github.com/woocommerce/wc-admin/commit/ff797eb1aeb6ac7bc225094257e31ddcecdd6467#diff-8d92651fcf148dca4a6ccd7e2f72fe2b) there was an import to `lib/number`, but that file doesn't exist outside of wc-admin. So I get this error:

```
ERROR in ../woo-dash/packages/currency/build-module/index.js
    Module not found: Error: Can't resolve 'lib/number' in '/packages/currency/build-module'
```

We can move `lib/number` to packages, or use a different function here?

**Comment by jeffstieler** [comment]
+1 for moving `lib/number` to packages

**Comment by timmyc** [comment]
I concur, definitely those util methods will be of use to extension developers.
