### ISSUE TITLE
Product report displaying inaccurate hourly data on chart

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1414]
The times are off in the product report. (pictured below) My store is set to Los Angeles time, which means I placed this order in the 2pm hour. It looks like it's calculating off of GMT. (+8hrs) 

<img width="1120" alt="screen shot 2019-01-29 at 2 28 14 pm" src="https://user-images.githubusercontent.com/4500952/51945535-d8918d80-23d3-11e9-8837-7708c3e17a56.png">

However, it's interesting to note that the times ARE correct in the order report and the revenue report: 

<img width="1108" alt="screen shot 2019-01-29 at 2 25 57 pm" src="https://user-images.githubusercontent.com/4500952/51944893-fcec6a80-23d1-11e9-9c54-8ed63d7789b0.png">

<img width="1122" alt="screen shot 2019-01-29 at 2 41 52 pm" src="https://user-images.githubusercontent.com/4500952/51945625-15f61b00-23d4-11e9-9210-b452d03cd747.png">

**Comment by justinshreve** [comment]
Confirmed this is fixed by #1414, after rebuilding data.
