### ISSUE TITLE
404 request when comparing two products

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1424]
**To Reproduce**
- Go to the _Products_ report.
- Select _Product Comparison_ as the filter.
- Select two products to compare.
- Click on `Compare`.
- Check the `Network` tab in your browser devtools and verify there is a call to the endpoint `/wc/v4products` (notice the missing slash) that returned 404.
![image](https://user-images.githubusercontent.com/3616980/51979257-f7078f80-248c-11e9-9eb5-cbfee4c97805.png)

**Comment by justinshreve** [comment]
I can't seem to reproduce this on master. I don't get a 404. Along with #1425 (which I think is because of this issue), both are working for me.

Do you still get a 404 when testing https://github.com/woocommerce/wc-admin/pull/1391?

**Comment by Aljullu** [comment]
I can still reproduce the issue both in `master` and `add/product-detail-report`:

![peek 2019-01-31 14-41](https://user-images.githubusercontent.com/3616980/52057802-52598080-2566-11e9-91ef-d12e4b8f3fcb.gif)

I needed to merge `master` into `add/product-detail-report` to get it working, otherwise it was not building with this error:
```
[0] ERROR in ./packages/currency/build-module/index.js
[0] Module not found: Error: Can't resolve '@woocommerce/number' in '/var/www/html/woocommerce/wp-content/plugins/wc-admin/packages/currency/build-module'
```

I don't think that's related at all, but just wanted to point it out.

---

#1425 doesn't seem to be fixed for me either in any of both branches.

Am I missing something?  :confused:
