### ISSUE TITLE
Activity Panel: Orders: Fix customer name

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1428]
There are two issues with the customer name output on the orders activity card:

---

If an order does not have a first/last name for a guest, the string in the order card of the activity panel looks like this second order:

<img width="369" alt="screen shot 2019-01-30 at 9 33 00 pm" src="https://user-images.githubusercontent.com/689165/52026756-fc89c780-24d6-11e9-88b3-e31a95408dbd.png">

You can make the billing/shipping fields optional with our checkout field editor plugin.

---

The card does not seem to be pulling the stored customers name from the order

<img width="795" alt="screen shot 2019-01-30 at 9 38 26 pm" src="https://user-images.githubusercontent.com/689165/52026895-820d7780-24d7-11e9-9cec-59ebad184f06.png">

---

**To Reproduce**
* Remove the first/last name from an order or create an order with no billing first/last name.
* View order in the activity panel.
* Create an order with a registered customer. Notice the name doesn't display.

**Comment by joshuatf** [comment]
@justinshreve Do we just want to remove the "placed by {customer_name}" piece of this?

Or do we want to try and get names if they're filled in from the user profile and not filled in during in checkout?  If so, I'm thinking there are 2 ways to go about this:

1. Use the order stats endpoint to query orders instead and join the customers table.  We could then make sure the customer table gets populated with the correct information as well.
2.  Or we can include the customer name information in the current orders endpoint.

I'm thinking (1) from above is a better option, but wanted to get a second opinion before getting started.

**Comment by justinshreve** [comment]
(1) above sounds good to me.

Just a note that there is still the potential (depending on extensions/checkout fields) that there is still no customer name — so we should still have some logic to catch that if the API response is empty.
