### ISSUE TITLE
Activity Panel: Embedded panel appends `#/` to the URL

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#1433]
Embedding the activity panel on existing WooCommerce pages makes those URLs redirect to a version with `#/' appended.

Ie. if you go to `/wp-admin/edit.php?post_type=shop_order` you will be redirected to `/wp-admin/edit.php?post_type=shop_order#/`. Can we disable this?

**Comment by ryelle** [comment]
We've noticed the same problem in the woo blocks, from using the `@woocommerce/components`, which includes the `@woocommerce/navigation` package: https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/327
