### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by top-master** [woocommerce/wc-admin#1434]
**problem:**
there is no `LICENSE` file in the project

**solution I'd like:**
Adding an `Apache 2.0` copy into `LICENSE` file would be more then enough.

**Alternatives I've considered:**
the `BSD` and `MIT` license's are really popular and they do make things lot easier,
Humans have a short live, who knows how many hours this project did require,
In short any license is better than `GPL`

**Should this be prioritized? Why?**
I would like to start using and maybe extending and developing on this project but can not do that unless there is a LICENSE file in the project, if there are multiple contributors this could also in the end lead to no one having full authority on the project

**Additional context**
It would take lot of time and efforts to latter change the license to `Apache 2.0`,
it is best to do it at the begin see below for a license change example:
SoftEtherVPN/SoftEtherVPN/issues/516

**Comment by justinshreve** [comment]
Thanks for letting us know about the missing LICENSE file! We will get that fixed up. 

We do mention the license in the contributing file, but it's a bit buried. Our license is already GPLv2 https://github.com/woocommerce/wc-admin/blob/master/CONTRIBUTING.md#license.
