### ISSUE TITLE
Component: Button

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#145]
Child issue of #144 

**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14683254/305328643/preview)

![image](https://user-images.githubusercontent.com/22080/42191806-c06f64d0-7e19-11e8-8d6d-34d2787f4bac.png)

While we should be able to leverage ( and already do ) the `<Button />` from `@wordpress\components` this task involves validating that all requisite styles/states from the hi-fi designs are in place for usage in `wc-admin`

**Comment by psealock** [comment]
This one has been resolved
