### ISSUE TITLE
'reports/taxes' and 'reports/taxes/stats' should allow limiting the results per tax id

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1456]
In order to allow searching tax codes in the _Taxes_ report table, we need the `reports/taxes` and `reports/taxes/stats` endpoints to support a new parameter (for example, `taxes`) which would accept a list of ids in order to limit the result set to those specific taxes ids.

Similar to the `products` parameter in the `reports/products` and `reports/products/stats` endpoint.

**Comment by timmyc** [comment]
@rrennick this is a fully REST issue that might be a good one to look into

**Comment by rrennick** [comment]
The `taxes={tax_rate_id}` is already in place for both `reports/taxes` and `reports/taxes/stats`. 

Use `https://example.com/wp-json/wc/v4/taxes/` to get the list of tax rate IDs then use `https://example.com/wp-json/wc/v4/reports/taxes/[stats]?taxes=ID` to see the stats for that tax rate.

**Comment by Aljullu** [comment]
Confirming what @rrennick said, this is already implemented.

Thanks for taking a look, I will close this issue.
