### ISSUE TITLE
'reports/customers' should allow limiting the results per user id

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#1457]
In order to allow searching customers in the _Customers_ report table, we need the `reports/customers` endpoint to support a new parameter (for example, `customers`) which would accept a list of ids in order to limit the result set to those specific user ids.

Similar to the `products` parameter in the `reports/products` endpoint.

**Comment by peterfabian** [comment]
When you say `customer_id`, is it `customer_id` or `user_id` from the `wc_customer_lookup` table?

**Comment by Aljullu** [comment]
Good question. It should be `user_id`, so it matches the `id` attribute returned by the [Customers WC endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#customer-properties).

I updated the issue title/text to make it more clear.

**Comment by Aljullu** [comment]
After #1534 was merged. I think we don't need to fix this issue anymore.
