### ISSUE TITLE
analytics showing no data 

### ISSUE THREAD

**Issue by myfriendmike** [woocommerce/wc-admin#1471]
**Describe the bug**
All analytics empty despite data being available for sales etc in Woocommerce for selected period/date range.

**To Reproduce**
No steps required
Steps taken to rule out possible causes (I'm no developer)
Twenty Fifteen theme activated.
All other plugins unrelated to Woocommerce deactivated.

**Expected behaviour**
I would expect there to be some information displayed in all graphs.

**Screenshots**

**Desktop (please complete the following information):**

wc-admin v 0.6.0
OS 10.13.6 OS High Sierra
Google Chrome v 71.0.35789.98 (64 bit)

**Additional context**

Graphs work as expected in the original woocommerce reporting.

**Comment by myfriendmike** [comment]
having read the following Issue: Dashboard not showing any data #1441
I have taken the advise of thomas-zg and used «Rebuild reports data» in the Status->Tools section.
This appears to have initially helped.

**Comment by claudiosanches** [comment]
@myfriendmike yes, all data need to be indexed into new tables, that's why initially there is no data.
Closing it in favor of #1441
Thanks for reporting.
