### ISSUE TITLE
Orders with excluded statuses count towards returning customers

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1473]
**Describe the bug**
Returning customers checks to see if an order was previously made by a customer in https://github.com/woocommerce/wc-admin/blob/ac4f8a4da7a1e0f9cc54e5f40b7a825bc0e07e28/includes/data-stores/class-wc-admin-reports-orders-stats-data-store.php#L504

Orders that fall into the excluded statuses can still mark a customer as "returning."  Should a customer only be marked as "returning" if they've had a previously successful order?

**To Reproduce**

1. Create a first order by a customer and set to an excluded order status (trash, failed, cancelled, refunded are defaults).
2. Create a second order by the same customer on a different date.
3. Select the date from the second order (not including the date from the original order so that the customer would not qualify as "new").
4.  Note that the customer is marked as "returning" even though the first order failed so they should technically be a new user.

**Expected behavior**
Expected the user to be "new" since the first order never succeeded.

**Additional context**
We can use the excluded statuses array to easily check inside `is_returning_customer()` however this would probably also require us to update ALL orders if the excluded statuses setting is changed to retroactively mark orders as returning in the `wc_order_stats` table.

Furthermore, we would also need to check all orders by a customer and update if a status is changed on a previous order.

**Comment by joshuatf** [comment]
This issue is blocked by #1504.

Once #1504 is merged in, the status checks should be placed into the order save hook that updates `date_first_order` in the customers lookup table.

**Comment by timmyc** [comment]
This is a tricky one. I'm inclined to support the excluded statuses in the `is_returning_customer` logic, that makes sense, but I'm hesitant to re-generate the entire customer lookup table if the excluded stati change.

Another wrinkle to this is what will happen if/when an extension manipulates order status logic?

I'm thinking we do add the support in `is_returning_customer` and then add messaging to the wc-admin settings page that inform the user they will need to re-populate the lookup tables if they wish to have past data updated to the new settings.

My fear is if we go down the road of updating the lookup tables en-mass anytime the settings change, that could get out of hand pretty quick on a site with poor hosting.
