### ISSUE TITLE
Breadcrumbs header triggering history

### ISSUE THREAD

**Issue by coderkevin** [woocommerce/wc-admin#1480]
The breadcrumbs header is calling `getPersistedQuery` from `@woocommerce/navigation`, which triggers `createHashHistory()` even when lazy-creating. In certain cases, this is not desired (e.g. when accessing a single order page, `http://my_wordpress_site.local/wp-admin/post.php?post=12345&action=edit`). The hash history created causes the page to reload with a `#/` suffix.

**Comment by justinshreve** [comment]
Related: #1433.
