### ISSUE TITLE
DB table initialization/update runs on the front end

### ISSUE THREAD

**Issue by rrennick** [woocommerce/wc-admin#1509]
**Describe the bug**
`WC_Admin_Api_Init::create_db_tables()` is executed on every front end page load (`WP_DEBUG` enabled). It also runs 18 `ALTER` statements each time. I checked the first table being updated and it already had the target schema of the `ALTER` statement. 

**To Reproduce**

1. Activate the query monitor
2. Load the shop
3. Check the queries starting somewhere in the mid 20s.

**Expected behavior**
The DB update routine should only run in the dashboard even when it's a development install. `ALTER` should only be executed when the target object doesn't match the required schema.

**Comment by timmyc** [comment]
Great catch @rrennick

**Comment by peterfabian** [comment]
Good to have this logged. This was actually done on purpose, IIRC @allendav added this a while back so that we could easily test different branches without having to remember apply db changes, if there were any.

**Comment by rrennick** [comment]
> we could easily test different branches without having to remember apply db changes

That makes sense. The catch is that switching branches doesn't unapply the DB schema changes so any changes would need to be backward compatible.

**Comment by jeffstieler** [comment]
Are we considering this resolved by #1510, or is there more to be done?

**Comment by rrennick** [comment]
#1510 addresses this fine by me.
