### ISSUE TITLE
REST API: Stock Stats Endpoint

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1527]
The final piece needed for the Stock Report ( #174 ) is the ability to retrieve stock totals to display in the footer of the report:

![image](https://user-images.githubusercontent.com/22080/42393694-13abdd6e-810c-11e8-9272-d0d9ccfb471e.png)

I initially thought we could possibly add the values needed to the `totals` portion of the `reports/products/stats` endpoints, but that endpoint is date-based so it just didn't feel like a correct place to put this data. And furthermore I feel having a particular `reports/stock/stats` endpoint might be of use in showing the "unread" notification in the Stock Activity panel eventually - and I could see the endpoint being valuable to the mobile apps.

Essentially I'm thinking of a very minimal endpoint that does not accept any arguments, and returns a payload with the following product stock totals returned for each `wc_get_product_stock_status_options()` ( like we have in the stock report [here](https://github.com/woocommerce/wc-admin/blob/master/includes/api/class-wc-admin-rest-reports-stock-controller.php#L105-L112), so would return something like:

```
{
  products: (int),
  lowstock: (int),
  instock: (int),
  outofstock: (int),
  onbackorder: (int),
}
```

I think it would also be prudent to have some aggressive caching on this endpoint due to the meta queries

**Comment by justinshreve** [comment]
I started working on this tonight when I grabbed #920 from Sprint 12.
