### ISSUE TITLE
Order Card: Update Collapsed Design

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#156]
Child issue of #144 

**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14683254/305328642/preview)

![image](https://user-images.githubusercontent.com/22080/42249562-d386eabc-7ee0-11e8-9688-2e2f8a0fe9fa.png)

This issue is blocked by many of the components outlined in #144. Once those are in place, this task will involve bringing them all together and implementing the collapsed order card view.

**Comment by justinshreve** [comment]
The collapsed view has been implemented. I noticed a couple issues with the customer name and logged them here: https://github.com/woocommerce/wc-admin/issues/1428.
