### ISSUE TITLE
Advanced Filters: Long Token-Field Names Hidden in Narrow Viewports

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1575]
**Describe the bug**
When an advanced filter of the token-field variety ( i.e. Products selected ) has a long name/value, the token field overflows off the screen and can not be fully seen. Furthermore, this prevents the (x) from being clicked on to remove a single selection... the only option is to use the "Clear All Filters" and start over.

![image](https://user-images.githubusercontent.com/22080/52833185-8c5f7200-3090-11e9-9420-b0b13f8452b7.png)

**To Reproduce**
Steps to reproduce the behavior on an emulator, phone, or resized browser window

1. Have a product with a really long name ( make a few, they are handy! )
2. Open the Products Report, Select Comparison, Pick your long-named product
3. Notice the token/tag overflows the container

**Expected behavior**
The ability to fully see the selected items, and remove them if desired.

**Comment by joshuatf** [comment]
@timmyc Nice find!

Should we display the whole name here or use an ellipsis if too long?  It looks like the current "Gutenberg-way" is to use an ellipsis.

<img width="358" alt="screen shot 2019-02-15 at 5 47 35 pm" src="https://user-images.githubusercontent.com/10561050/52848651-35b66e80-314a-11e9-8577-bc21974fe414.png">

**Comment by timmyc** [comment]
I think following the Gutenberg pattern with the ellipsis works well but /cc @josemarques and @LevinMedia just in case
