### ISSUE TITLE
Advanced Filters: Match Filters Drop-Down Missing Arrows in Narrow Viewports

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1577]
**Describe the bug**
When viewing Advanced Filters in a narrow viewport - the "Matches All/Any" drop down is missing arrows, and is hard to tell if it is a form control that can be interacted with, or just text with a line around it.

![missing-arrows-on-select](https://user-images.githubusercontent.com/22080/52834464-d186a280-3096-11e9-9944-c7768eae9b8c.png)

**To Reproduce**
Steps to reproduce the behavior on a mobile device or emulator

1. Open a report with Advanced Filters
2. Expand the advanced filters, note the screenshot above

**Smartphone (please complete the following information):**

Chrome in emulator mode, Pixel XL2

**Additional context**

**Comment by Aljullu** [comment]
@timmyc I can't reproduce this issue, maybe it's Mac-specific?

![image](https://user-images.githubusercontent.com/3616980/52856778-a008e800-3125-11e9-896f-df6adf71c3df.png)

**Comment by timmyc** [comment]
Appears like it might just be chrome - firefox looks fine, and here is mobile safari:

![image](https://user-images.githubusercontent.com/22080/52872246-db44f000-3100-11e9-9d74-d945c285ded6.png)

**Comment by justinshreve** [comment]
Does anyone have an Android phone to see if this happens on a device?

We could try adding our own image as the arrow if it seems worth it for mac chrome.

**Comment by joshuatf** [comment]
I can still see it in narrow viewports unless the device mode is enabled.  I think this may just be a bug using the Chrome inspect device tool.  @timmyc Can you confirm that's what you were using?

Here's a screenshot from a meta box on a non-wc-admin page and also the same behavior outside of WP.
<img width="328" alt="screen shot 2019-02-20 at 1 21 25 pm" src="https://user-images.githubusercontent.com/10561050/53068195-9101ab80-3512-11e9-8be1-ba4d445b25c9.png">
<img width="331" alt="screen shot 2019-02-20 at 1 20 07 pm" src="https://user-images.githubusercontent.com/10561050/53068196-9101ab80-3512-11e9-9c2d-2b6f448caaaf.png">

**Comment by timmyc** [comment]
Confirmed it is indeed just a bug in device mode in chrome, sorry for the false alarm - screenshot from Pixel:

![image](https://user-images.githubusercontent.com/22080/53117172-2a26c700-34ff-11e9-843a-47b76edf7d07.png)
