### ISSUE TITLE
Design: Date Range Picker Updates / Enhancements 

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#159]
Add designs for custom date range picker: p6riRB-3iy-p2

- [ ] Create responsive sketch compent based off of react-dates default
- [ ] Update colors
- [ ] Include Form preivew text
- [ ] Include Invalid entry state + tool-tip

General

- [ ] Add focus state for presets / custom segmented controls (dependent on larger focus state conversation)

Related to: #149

**Comment by psealock** [comment]
I'm pretty sure this has been addressed so I'm closing
