### ISSUE TITLE
Downloads Report Table missing User Name value

### ISSUE THREAD

**Issue by jeffstieler** [woocommerce/wc-admin#1614]
**Describe the bug**

The downloads report table never displays "user name". (The endpoint provides `user_id` but not `username` or customer name)

This missing value also breaks CSV downloading (console error).

**EDIT:** This is caused by a plugin that disabled the `/wp/v2/users` endpoints - solution is to embed the necessary product/user data in the `/v4/reports/customers/` endpoint rather than rely on embeds from other namespaces.

Found testing #1523.

**To Reproduce**

1. Go to Downloads Report (where there is data)
2. Verify that User Name column is empty for all rows

**Expected behavior**

I expect the customer's name or username to display.

**Screenshots**

![screen shot 2019-02-18 at 4 30 06 pm](https://user-images.githubusercontent.com/63922/52981106-caafa680-339a-11e9-94f7-0e7128e2622d.png)

**Comment by justinshreve** [comment]
I'm not able to reproduce this one @jeffstieler:

<img width="1056" alt="screen shot 2019-02-19 at 12 25 31 am" src="https://user-images.githubusercontent.com/689165/52991979-f05d9f80-33dc-11e9-9d57-e782a66e6787.png">

The response is part of the `_embedded` object (https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_embed):

https://gist.github.com/justinshreve/f52b09d19198221e67e4d4d742a5d2b4

**Comment by jeffstieler** [comment]
@justinshreve it seems that on my test site, the `/wp/v2/users` endpoint is disabled. What do you think about directly including the data we need for display in the endpoint response rather than relying on embeddable objects?

**Comment by justinshreve** [comment]
> What do you think about directly including the data we need for display in the endpoint response rather than relying on embeddable objects?

That sounds good to me.
