### ISSUE TITLE
Duplicate API request when comparison items are set

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1638]
**Describe the bug**
When 2 or more items have been selected to compare, a duplicate API request is made.  It seems like this can be traced back to `getLabel()` which may be called in both the table header and the advanced filter.

**To Reproduce**

1. Go to the products report.
2. Select 2 items to compare in the advanced filter and click "compare."
3. Refresh the page.
4.  Note the 2 API requests and items only shown in the advanced filter (not on top of the products table).

**Expected behavior**
Expected a single API request or if that's not an option, the 2nd comparison field should show labels for the selected values (currently the table does not show the comparison items).

**Screenshots**
<img width="563" alt="screen shot 2019-02-20 at 3 49 28 pm" src="https://user-images.githubusercontent.com/10561050/53075120-62420000-3527-11e9-9d0e-5af0c20f77fd.png">
<img width="730" alt="screen shot 2019-02-20 at 3 49 25 pm" src="https://user-images.githubusercontent.com/10561050/53075122-62da9680-3527-11e9-8149-fd9d111ac029.png">

**Comment by justinshreve** [comment]
Related: #1453.

**Comment by joshuatf** [comment]
@justinshreve Thanks for noting that!

@Aljullu If a comparison has been made, is the search box above the table supposed to also show identical tags to that of the advanced filter?

**Comment by Aljullu** [comment]
> @Aljullu If a comparison has been made, is the search box above the table supposed to also show identical tags to that of the advanced filter?

AFAIK, no. The table search should be completely independent of the comparison.

I found a bug related to that, however: #1660.

**Comment by joshuatf** [comment]
Okay, I'll close this issue then as it appears to be a duplicate of #1453.
