### ISSUE TITLE
Search query is ignored in tax REST API

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1639]
**Describe the bug**
Searching for tax codes to compare on the tax report does not use the search term, but instead returns a list of tax codes (presumably ordered by id or tax class) limited to 10 results.  This will be problematic if more than 10 exist.

There doesn't seem to be a `search` collection param for the tax rest controller.

**To Reproduce**

1. Create more than 10 tax codes.
2. Search for tax codes in the comparison filter on the tax report.
3. Note that you won't be able to find all tax codes.

**Expected behavior**
Expected to be able to find tax codes by search.

**Screenshots**
<img width="1172" alt="screen shot 2019-02-20 at 4 06 56 pm" src="https://user-images.githubusercontent.com/10561050/53076064-b221c680-3529-11e9-9636-06b8cd88c12a.png">

**Comment by psealock** [comment]
Just to note: The tax REST API also does not accept an `include` parameter as the other endpoints do.
