### ISSUE TITLE
Taxes Core REST API: Add collection param 'include'

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1640]
**Describe the bug**
When adding tax items through the comparison filter, refreshing the page (and occasionally on adding new items) does not get the correct labels.

This bug is caused by the `getLabels()` call to the tax controller since the tax controller does not inherit from `WC_REST_CRUD_Controller` there is no collection param for `include` to filter results.

**To Reproduce**

1. Add a couple tax labels in the comparison filter (not in order of database IDs).
2. Click "Compare."
3. Refresh the page.
4. Note that the labels are incorrect.

**Expected behavior**
Expected the correct labels to be retrieved.

**Screenshots**
![feb-20-2019 16-21-11](https://user-images.githubusercontent.com/10561050/53076832-9f0ff600-352b-11e9-9bb9-b6b3c91dafbd.gif)

**Comment by psealock** [comment]
A fix for this is in progress https://github.com/woocommerce/wc-admin/pull/1571

**Comment by joshuatf** [comment]
Thanks for handling the labels and updating this @psealock.

Note on this issue: labels are now fixed in #1571 so this issue will involve creating an `include` param to filter taxes.
