### ISSUE TITLE
Product and customer report fail to download CSV

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1643]
**Describe the bug**
Visiting the product or customer reports without adding any query parameters results in an error being thrown when clicking "Download."  Adding any filters seems to allow downloading.

**To Reproduce**

1. Go to the products or customers report.
2. Click "Download."
3. Note the console error.

**Expected behavior**
Expected the CSV to download without fail.

**Screenshots**
<img width="502" alt="screen shot 2019-02-20 at 4 51 13 pm" src="https://user-images.githubusercontent.com/10561050/53079169-d208b880-3530-11e9-8827-c5cec7aafce7.png">

**Comment by Aljullu** [comment]
I can't reproduce this issue, it seems to be working fine for me:
![download](https://user-images.githubusercontent.com/3616980/53104859-6cb4c780-3530-11e9-8bfb-64a18acd9524.gif)

The line producing the error is:
https://github.com/woocommerce/wc-admin/blob/master/packages/csv-export/src/index.js#L16

I would say checking `rowItem.value` exists before performing `toString()` would fix the issue, but I would need to be able to reproduce it to confirm.

**Comment by joshuatf** [comment]
>I would say checking `rowItem.value` exists before performing `toString()` would fix the issue, but I would need to be able to reproduce it to confirm.

Thanks for looking into this @Aljullu!

I'll take another look today and see if I can spot the root cause.  May be specific to my data.
