### ISSUE TITLE
REST API: Month, Quarter, Year to Date Including Prior Day

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1651]
**Describe the bug**
When requesting data for presets of Month/Year/Quarter to date, the REST API response is including the prior day in the intervals response.

**To Reproduce**
Use a preset on any report page to use Month/Quarter/Year to date, or use Postman to do a request like

GET `/wp-json/wc/v4/reports/revenue/stats?after=2019-01-01T00%3A00%3A00%2B00%3A00&before=2019-02-20T23%3A59%3A59%2B00%3A00&interval=day&order=asc&per_page=100&_locale=user`

Note that an interval for 2018-12-31 is included in the response:

![image](https://user-images.githubusercontent.com/22080/53134701-067a7580-352d-11e9-89ba-881582308753.png)

**Comment by psealock** [comment]
Maybe this is timezone related because i can't reproduced this one in Postman nor our interface.

**Comment by timmyc** [comment]
Yeah I'm guessing it likely is TZ related.

**Comment by jeffstieler** [comment]
I'm also unable to reproduce this with my local environment - can you perhaps provide a DB export?

**Comment by timmyc** [comment]
@jeffstieler I'll send you a link to a backup where it is still happening for me.
