### ISSUE TITLE
Navigating to different routes doesn't close the side menu

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1657]
**Describe the bug**
When clicking a navigation item on smaller screen sizes, the side menu doesn't close when navigating between wc-admin pages.

**To Reproduce**

1. Go to any wc-admin page.
2. Navigate to another wc-admin page to take advantage of the router.
3. Note that the menu stays open.

**Expected behavior**
On a smaller screen, I was caught off guard when this happened and thought the page was still loading.  The menu should probably close after changing routes.

**Screenshots**
![feb-21-2019 15-49-37](https://user-images.githubusercontent.com/10561050/53152448-89183900-35f0-11e9-8e46-2d06805f95c7.gif)

**Comment by Aljullu** [comment]
I think that was fixed in #1634.

**Comment by justinshreve** [comment]
I just tested again on `master` and this is closing for me as of the fix in #1634. Can you update and test again? If it's still not working, what browser?

**Comment by joshuatf** [comment]
@justinshreve You're right- this is resolved.  Closing this issue.
