### ISSUE TITLE
Zero value items aren't shown when comparing items

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1668]
**Describe the bug**
When selecting 2 or more items to compare, an item that is zero value (e.g., a product without sales during a given period) is not shown on the table.

Not urgent, but might be nice to show all the items being compared, even if they are zero.  Thoughts?

**To Reproduce**

1. Go to the products report.
2. Compare a product with sales during a given period and another without sales during that same period using the advanced filter.
3.  Note the table does not include the second product being compared.

**Expected behavior**
Expected all items being compared to show up in the table.

**Screenshots**
<img width="771" alt="screen shot 2019-02-22 at 9 49 47 am" src="https://user-images.githubusercontent.com/10561050/53214709-98e35c00-3688-11e9-90b4-5dd69d0ad6f8.png">
<img width="487" alt="screen shot 2019-02-22 at 9 49 37 am" src="https://user-images.githubusercontent.com/10561050/53214710-98e35c00-3688-11e9-9166-396591080d1e.png">

**Comment by Aljullu** [comment]
I think that's related to #1398.

**Comment by Aljullu** [comment]
Closed by #1765.
