### ISSUE TITLE
Deleting a product after an order was made creates a 500 error

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#1669]
**Describe the bug**
If an order is made with a product and that product is subsequently permanently deleted, an error will be thrown on the products report.

Big thanks to @LevinMedia for finding this bug!

**To Reproduce**

1. Make an order.
2. Delete a product in that order (permanently).
3. Go to the products report.
4. Select a date range with that order in it.
5. Note the error.

**Expected behavior**
Expected to still be able to see the report.  For items that were deleted, we only store quantity and revenue amounts, no names, skus or other information.

@LevinMedia Should we continue to show the product but in place of unknown fields add something like `(Deleted)`?  Or do we exempt these rows from the products report?

**Screenshots**
<img width="869" alt="screen shot 2019-02-22 at 12 56 51 pm" src="https://user-images.githubusercontent.com/10561050/53220807-6003b100-36a1-11e9-932e-ecc6549607c6.png">

**Additional context**
The 500 error originates from a product not being found [here](https://github.com/woocommerce/wc-admin/blob/2d0b05c9ebd19746048164ddbaa0a639fe97b433/includes/data-stores/class-wc-admin-reports-products-data-store.php#L200).

In addition to checking if a product was found, we may also want to forego some of the JOINS in this data store if the `product_id` is 0.  

Finally, deleting a product should probably trigger updates to any orders it's in within the orders lookup table if we're checking for `0` values in `product_id` anywhere.

**Comment by LevinMedia** [comment]
>Should we continue to show the product but in place of unknown fields add something like `(Deleted)`? Or do we exempt these rows from the products report? I

Heya @joshuatf thanks for logging this! We should keep the deleted products in the report for sure. I would it be possible to keep the name and sku but insert `[Deleted]` before the name?

**Comment by joshuatf** [comment]
>I would it be possible to keep the name and sku but insert `(Deleted)` before the name?

@LevinMedia Not with the current setup.  @peterfabian Do you think we should store the product name and sku in the `wc_order_product_lookup` table?

**Comment by peterfabian** [comment]
I don't think we should store it in `wc_order_product_lookup`, feels like too much duplication to me. If you decide to delete your product, it goes without saying you lose some info. 😛 
However, I think the product name could be looked up in `woocommerce_order_items` and `woocommerce_order_itemmeta` tables. Not sure if it would be too costly/complicated to look it up?

However, I'm a bit afraid we need to test more similar scenarios for other objects, where deletion is a bit more probable:
- coupon updated/deleted -- what happens to segmentation by coupon, bucket for that coupon could be missing, unless it's saved in meta
- tax rate updated/deleted
- category updated/deleted

**Comment by joshuatf** [comment]
>However, I think the product name could be looked up in `woocommerce_order_items` and `woocommerce_order_itemmeta` tables. Not sure if it would be too costly/complicated to look it up?

I do think that's going to be pretty costly and we'd want to do this for all of our existing data and not just deleted items.  I imagine that's going to be strenuous on larger sites.

@LevinMedia I think it might be best to forego this information if they've deleted a product.  Any method that does this comes at a pretty high cost.  Is keeping `(Deleted)` an option or do you have other ideas you'd like to try here?

>However, I'm a bit afraid we need to test more similar scenarios for other objects

Good point and agreed.  Should we keep data for these items in the lookup tables if they exist already?  Amounts and IDs can all be kept and we'll only lose out on names if they've been permanently deleted.

**Comment by timmyc** [comment]
Another angle on this issue, when populating the lookup tables - the same scenarios will likely cause problems / exceptions

**Comment by jeffstieler** [comment]
It's unclear to me if there's an agreed upon solution here... is this ready to be worked on?

**Comment by LevinMedia** [comment]
Heya @jeffstieler  not yet, no.

@peterfabian I have a couple questions about what you posted earlier, in particular in regards to updating categories, coupons, and tax rates.  

Would this bug be triggered by updating the name of a tax rate, coupon, or category? If it triggers this bug in those instances, would it also trigger the bug if you updated a product name?

In all of the above cases, I would would expect the changed name to show up in place of the previous name throughout the reports. 

>Is keeping (Deleted) an option or do you have other ideas you'd like to try here?

In the short term, I think this might be our only realistic option.

**Comment by joshuatf** [comment]
>Would this bug be triggered by updating the name of a tax rate, coupon, or category? If it triggers this bug in those instances, would it also trigger the bug if you updated a product name?

@LevinMedia The way it's currently setup, updates to those are reflected instantly every time, so that the current (new name) will always show up.  If we changed to the alternative of using `woocommerce_order_itemmeta` then it would always show the name at the time the order was made and changes won't be reflected.

Since I don't think we'll be changing to `woocommerce_order_itemmeta` changes are not an issue, just deleting.  But feel free to correct me I'm wrong here @peterfabian.

>Another angle on this issue, when populating the lookup tables - the same scenarios will likely cause problems / exceptions

That's a good point @timmyc.  We should probably ignore my comment about leaving already synced data, however, I don't think it was applicable anywhere within the lookup tables anyway.  Deleted product and coupon IDs should still be available in `woocommerce_order_itemmeta` where they're pulled by WC functions like `$order->get_items()` when syncing.

**Comment by joshuatf** [comment]
Side note:  I opened an issue for deleted coupons [here](https://github.com/woocommerce/wc-admin/issues/1751).  Categories and taxes just don't show after they're deleted which I think is expected behavior.
