### ISSUE TITLE
Analytics: Orders Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#168]
Blocked by #97 

All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dO-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_orders_stats](get_reports_orders_stats)
**REST API Post**: p7bje6-14E-p2

__Child Issues__

- [x] Summary Numbers #410
- [x] Chart #417
- [x] Table #418

**Desktop**

![image](https://automattic.invisionapp.com/static-signed/live-embed/266158435/313168866/8/latest/VD6xOBMY1XvlElVuANfhoc3neY5ppZFLuKe79Lc1zhFw3lEb1VuFR3jbJ50ZQYtbyh9w1wNLGatustkKfV2pxSzQlE/Orders---Viewport-1366-2x.png)

Always reference the design post above for the most recent version of this screen

**Comment by LevinMedia** [comment]
Updated with hifi screens

**Comment by timmyc** [comment]
The child tasks have been completed and follow-up issues have been created. Closing this out.
