### ISSUE TITLE
Analytics: Products / Product Detail Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#169]
**Design Post**: p6riRB-3dP-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats](get_reports_products_stats)
**REST API Post**: TBD

![image](https://user-images.githubusercontent.com/22080/42393023-bfb68b7a-8109-11e8-8be5-2cbd00250e66.png)

- [x] #534 Chart & Summary Numbers
- [x] #535 Table
- [x] #536 Table Filter
- [x] #537 Comparison Filter

**Comment by psealock** [comment]
All tasks completed on this one. Remaining issues surrounding product detail view can be tracked in https://github.com/woocommerce/wc-admin/issues/564
