### ISSUE TITLE
Settings: Move Lookup Tables UI to Settings Page

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1691]
Currently the button that triggers the population of the report lookup tables lives in System | Tools page:

![image](https://user-images.githubusercontent.com/22080/53380058-dcf08e00-3920-11e9-8881-952e9b96b1b7.png)

@LevinMedia is in the process of coming up with some improved designs for this tool, but until those are completed, I think we should do the following items:

- [ ] Remove the button from the System | Tools page
- [ ] Build a new button on the Analytics | Settings page instead which triggers the action to populate the lookup tables
- [ ] When the button is clicked on the Analytics | Settings page - the button should be disabled to prevent double-submission ( and lots and lots of jobs being queued up.

**Comment by justinshreve** [comment]
@LevinMedia @timmyc Can we include a design for clearing pending jobs as well as a part of this issue? 

I have a PR about to go up for the backend of https://github.com/woocommerce/wc-admin/issues/1699 -- but I didn't want to put too much work in the UI until we now what it looks like.

--

My two cents on this moving the buttons: It also seems a little odd to me to move these tools out of system tools. Re-running and/or clearing out queued options seem like uncommon actions (except for the initial setup which can be handled by a note https://github.com/woocommerce/wc-admin/issues/1709) and putting them front and center on a settings page seems like it could be dangerous. These buttons are also at home already with other similar actions (clearing sessions, etc) and make sense for future core merge.

**Comment by LevinMedia** [comment]
@justinshreve 

>Can we include a design for clearing pending jobs as well as a part of this issue?

Affirmative. I want to include a Pause button and a clear button. 

> seems a little odd to me to move these tools out of system tools. Re-running and/or clearing out queued options seem like uncommon actions (except for the initial setup which can be handled by a note #1709) and putting them front and center on a settings page seems like it could be dangerous.

@josemarques and I had a conversation along these lines as well, it's a fair point. @timmyc mentioned it might be behoove us to use the new settings menu as it's powered by JS, rather than PHP, thus affording us more flexibility in design and usage of wc-admin components (such as a date range picker, if we wish to allow a store to process portions of their data at a time.) 

What if we were to show the settings conditionally, only when there is data that needs processing?

**Comment by justinshreve** [comment]
> What if we were to show the settings conditionally, only when there is data that needs processing?

Hmm -- I feel like that could be confusing to the user to have a section disappear and might be even more confusing (no tool under system status tools, and a disappearing tool under Analytics settings). I also wonder if we would be able to tell all the potential edge cases that needs processing.

>  thus affording us more flexibility in design and usage of wc-admin components

That's a good point about the date picker components -- I didn't think of that. If we have more granular options, it probably makes sense being under analytics settings for now. Maybe in the distant future we can make it so we can use components under system status tools ;). I just wanted to note some thoughts as I was digging around tools and Action Scheduler today.
