### ISSUE TITLE
Tracks: Use Woo Core's supplied method

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1697]
Currently our [track utility](https://github.com/woocommerce/wc-admin/blob/master/client/lib/tracks.js#L17) uses `wca_` as a prefix while the work that is being done for Woo Core is using `wcadmin_` https://github.com/woocommerce/woocommerce/pull/22851

For this simple task we should update our usage here to match that in core.

**Comment by psealock** [comment]
wc-admin can remove its enqueuing of `w.js` and its `recordTracks` function altogether in favour of Woo Core's method, `window.wcTracks.recordEvent`.

I changed the title to reflect this.

**Comment by timmyc** [comment]
Excellent call Paul!
