### ISSUE TITLE
Analytics: Categories Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#170]
Blocked by #97 

All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dR-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_categories_stats](get_reports_categories_stats)
**REST API Post**: p7bje6-151-p2

![image](https://user-images.githubusercontent.com/22080/42393153-4fb881c4-810a-11e8-9db2-baa6f26d01e1.png)

**Comment by justinshreve** [comment]
I'm reopening this and grabbing it. The categories report is still hooked up to SwaggerHub.

**Comment by justinshreve** [comment]
My bad - Paul pointed out #1284 existed and he's already working on it :).
