### ISSUE TITLE
Legend and tabular data not displaying when comparing series with no data present

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#1704]
**Describe the bug**
when comparing series and no data is present, the series in the legend disappear. All of the rows in the tabular data disappear too.  

**To Reproduce**
Create a comparison, select a date range with no data.
Note, the series in the legend disappear
Note the tabular data rows disappear

**Expected behavior**
Even if no data is available, the compared series should remain in the legend with zero values - as well as in the tabular data below (not pictured in screen shot) also with zero values. 

<img width="1380" alt="52029986-91d28f00-24ca-11e9-9a81-538cd0029ecc" src="https://user-images.githubusercontent.com/4500952/53508375-78dbe000-3a6e-11e9-8d17-975abbf0cebe.png">

**Previously noted in :** 
https://github.com/woocommerce/wc-admin/issues/582#issuecomment-459209125

**Comment by Aljullu** [comment]
I think this is the same as #1668. I'm currently working on that one, so I will make sure to verify this one is fixed as well when submitting a PR.

**Comment by LevinMedia** [comment]
Yeah for sure, the tabular data portion is the same as what I'm talking about here - I just want to make sure the absence of the legend is also address, whether that's in #1668 or another pr. 

Thank you!

**Comment by Aljullu** [comment]
Closed by #1765.
