### ISSUE TITLE
Notes: Populate Lookup Tables

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#1709]
Since we will no longer be populating the lookup tables automatically on install [ blocked sort of by #1666 ], we should also utilize the new Store Alert component to inform users to do so.

[How to create notes documentation](https://github.com/woocommerce/wc-admin/blob/master/docs/examples/activity-panel-inbox.md)

For the content of the note, how about we go with:

Title: "Reporting tables need to be updated"
Body: "In order to use the new analytics features of WooCommerce Admin, the reporting database tables need to be populated with historical data for your store. All new orders and customers will automatically be viewable within the reports, but in order to view past orders and customers, you will need to populate the lookup tables."
Action Button: "Update Report Tables" - which will run `WC_Admin_Reports_Sync::regenerate_report_data();`

/cc @LevinMedia for copy check

Eventually I think we should also link to documentation on how to configure Action Scheduler for higher volume sites.

**Comment by justinshreve** [comment]
> Action Button: "Update Report Tables" - which will run
> WC_Admin_Reports_Sync::regenerate_report_data();

Should we instead link them to the settings page being designed so they can select a time period?
