### ISSUE TITLE
Analytics: Coupons Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#171]
Blocked by #97 

All base analytics components are being developed for the Revenue Report. Once those components ship, work can commence on this report.

**Design Post**: p6riRB-3dS-p2
**Mock API**: [https://href.li/?https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_coupons_stats](get_reports_coupons_stats)
**REST API Post**: p7bje6-15o-p2

__Child Issues__

- [x] Summary Numbers (#837)
- [x] Chart (#836)
- [x] Table (#835)
- [x] Update API endpoints #845
- [x] Hook up live data #940

![image](https://user-images.githubusercontent.com/22080/42393260-aac369ee-810a-11e8-995b-a418b549f66e.png)

__Follow-Up Tasks__
From #418 - once this report lands, we need to revisit the Orders report and link the coupon fields there to their corresponding Coupon Report.

**Comment by Aljullu** [comment]
@timmyc I created three child tasks (Summary Numbers, Chart and Table) as we did for the Orders Report (#168) so it's easier to keep track of the progress.

**Comment by timmyc** [comment]
Thank you @Aljullu !

**Comment by joshuatf** [comment]
Closed by #724, #867, #1010 and #1112.
