### ISSUE TITLE
Analytics: Taxes Report

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#172]
**Design Post**: p6riRB-3dT-p2
**Mock API**: [https://href.li/?https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_taxes_stats](get_reports_taxes_stats)
**REST API Post**: p7bje6-15p-p2

__Child Issues__

- [x] Table (#875)
- [x] #844 REST Endpoints
- [x] #923 Analytics: Taxes Report Chart
- [x] #924 Advanced Filters
- [x] #941 Hook up REST API Data

![image](https://user-images.githubusercontent.com/22080/42393426-345afb86-810b-11e8-81ff-fbae264bda5c.png)

**Comment by joshuatf** [comment]
Closed via #1019 #1000 #779 #999 and #1008.
