### ISSUE TITLE
Component: Inbox Card Unread

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#177]
Child issue of #176 
**Designs**: [inVision Project](https://automattic.invisionapp.com/d/main#/console/14671248/305076999/preview)

![image](https://user-images.githubusercontent.com/22080/42402779-d5d2a682-8131-11e8-8838-e94e5364822f.png)

See design link above for mobile + desktop viewport styling/spacing

**Comment by ryelle** [comment]
This was added to the ActivityCard base component in #203 - as long as the `unread` prop is true, there will be a little red dot 🙂
