### ISSUE TITLE
Product report layout broken, products report broken

### ISSUE THREAD

**Issue by ronakganatra9** [woocommerce/wc-admin#1777]
**Describe the bug**
delete the product which has been ordered and showing in reports, it will break the products page.

**VIdeo Link**
https://drive.google.com/file/d/1dP3iLa0bY5NTYaIJjExMW1sWDYCBDkXL/view?usp=sharing

**To Reproduce**

1. Create A product.
2. make an order with that created product.
3. check product analysis report on the dashboard or products tab in analytics
4. you will be able to see the product in that report.
5. Delete that product permanently.
6. Now check the products report
7. the page is broken

In the console you will find 500 error.

**Expected behavior**
It should either delete the row or should display the information properly.

**Screenshots**

![Screenshot from 2019-03-11 15-40-03](https://user-images.githubusercontent.com/24435113/54116157-28706500-4414-11e9-8463-11fdb58bc5d1.png)

Video Link:
https://drive.google.com/file/d/1dP3iLa0bY5NTYaIJjExMW1sWDYCBDkXL/view?usp=sharing

**Desktop (please complete the following information):**

* OS: Ubuntu
* Browser Chrome

**Additional context**
It stores product id in the product_lookup table so the product is deleted and it is not finding the product table so we must save product name in the table. The same thing applies to coupon also.

**Comment by Aljullu** [comment]
Thank you @ronakganatra9 for testing `wc-admin` and filling an issue! It looks like this issue is the same as #1669. Given that there has been some discussion going on in that one, I will proceed closing this one in favour of #1669.

Feel free to create a new issue if you find any other bug.

**Comment by ronakganatra9** [comment]
Sorry, Didn't see that the issue is created.

Thanks for your reply.

Thanks,
Ronak
