### ISSUE TITLE
Analytics: Revenue Report API/data-layer

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#224]
Child task of #97

**API Post / Schema**:  p7bje6-14c-p2

This issue encompasses creation of the `wp.data` API logic to support the needs of the Revenue Report. The p2 post linked above outlines the three requests needed to power the summary numbers, charts, and tabular data.

**Comment by justinshreve** [comment]
The revenue endpoint is still in development. The current branch fatals out, so I'll hold off on this for now. It sounds like the endpoint should make it in this Wednesday.
