### ISSUE TITLE
DatePicker: Viewport oddities

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#252]
From https://github.com/woocommerce/wc-admin/pull/239#issuecomment-408954708

>I'm still seeing a bit of oddness with the same issue I described above. Almost seems like my viewport height is at some in-between spot that is preventing the scrolling from happening. If I shrink the viewport a smidge, it works as expected.

To reproduce: 

1. `/wp-admin/admin.php?page=wc-admin#/analytics/products`
1. Open the datepicker
1. Shrink the viewport to just the height of the datepicker
2. Switch to Custom tab, which is longer than the Presets tab
3. See the scrollbars don't appear and the bottom of the datepicker is inaccessible

**Comment by timmyc** [comment]
<img width="468" alt="z-index-jank" src="https://user-images.githubusercontent.com/22080/43428622-0f341d4e-9414-11e8-8486-f038e1a92970.png">

`z-index` issue can be seen in the screenshot above.

**Comment by psealock** [comment]
I'm reopening this issue because only the z-index issue was resolved. The viewport on Popover not responding to content height issue remains.

**Comment by timmyc** [comment]
Since this is blocked upstream I'm moving this to the project backlog.
