### ISSUE TITLE
Extensibility: Lerna for Reporting Modules

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#254]
One of the big extensibility goals for v1 is going to be enabling developers to leverage our components which are being developed for Woo Core Analytics, in their own custom reports for their extensions.

So prior to us getting too far into developing many-a-report, this task should explore and implement any changes to folder structure in the project to ensure we can leverage [lerna](https://lernajs.io/) to build report-specific components for 3rd Party Developers to leverage.

Stretch goal... do we consider building something similar to create-guten-block to build out a scaffold of a report for developers? Seems like with good documentation that is likely not needed, and many developers will probably be adding reports to existing extensions.

**Comment by justinshreve** [comment]
Does anything else need done for this issue as part of sprint 2 specifically? Just wondering if we can close it out (I know there is more work to be done in future sprints such as documentation and other things we may uncover).

**Comment by ryelle** [comment]
I think we've determined that we're not going to use Lerna to start with, so I think this can be closed out. Having documentation and/or a pattern library up would be a great thing, but not required in this sprint IMO. Does that sound right, @timmyc?

**Comment by timmyc** [comment]
Yep I think with #298 merged we can close this out. We can push for some docs/example plugin in a future sprint. Thanks for the work here @ryellle!
