### ISSUE TITLE
Component: Search Box

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#257]
**Designs**
Filter Picker: p6riRB-3lk-p2
Advanced Filters: p6riRB-3mb-p2

![screen shot 2018-08-01 at 12 15 48 pm](https://user-images.githubusercontent.com/1922453/43494060-fee7fdc6-9584-11e8-8652-3f0b87922a74.png)

![screen shot 2018-08-01 at 12 18 36 pm](https://user-images.githubusercontent.com/1922453/43494067-0a2ac092-9585-11e8-832e-108f7faa1843.png)

- [x] Products #322 
- [ ] Coupons #342 
- [x] Customers
- [x] Orders
- [x] Product Category #343

**Comment by timmyc** [comment]
Noting some prior art in Gutenberg can be seen when using the link dialog to attach links to existing posts:

![image](https://user-images.githubusercontent.com/22080/43863558-eff1a744-9b11-11e8-9129-5cbccac1d931.png)

**Comment by timmyc** [comment]
Also seems autocompleters would be of use here https://github.com/WordPress/gutenberg/tree/94f54892c214ebd014ec126a9575b7e902198ad9/packages/editor/src/components/autocompleters
