### ISSUE TITLE
Component: Advanced Filters: CRUD URL query parameters 

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#261]
**Designs**: p6riRB-3mb-p2

Enable Advanced Filter Component to read and update URL parameters to persist filter terms

![screen shot 2018-08-01 at 12 30 02 pm](https://user-images.githubusercontent.com/1922453/43494393-b21bda9c-9586-11e8-869e-ea74da068f81.png)

**Comment by ryelle** [comment]
I started on this idea a little with the table ordering – I pulled out [`updateQueryString` into the nav-utils lib](https://github.com/woocommerce/wc-admin/blob/master/client/lib/nav-utils.js#L22), which quietly updates the URL. We should try to keep all query manipulation in this file, if we can.

**Comment by psealock** [comment]
@ryelle Thanks. I have been using a similar function that creates a url for `<Link />` component. I can integrate those into this file in an upcoming PR

**Comment by timmyc** [comment]
I _believe_ this is already taken care of, so closing this out. Please re-open if it isn't fully baked yet @psealock
