### ISSUE TITLE
Component: Advanced Filters: Download Report

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#263]
**Design Post**: p6riRB-3dU-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_stats](get_reports_downloads_stats)
**REST API Post**: p7bje6-15q-p2

The downloads report needs to support the following Advanced Filters:

- `product` one or more, akin to the orders report
- ~`filename` one or more file names~
- `order` input an order number to filter by
- `user` input a username to filter
- `ip` filter by IP address

![screen shot 2018-08-01 at 12 34 48 pm](https://user-images.githubusercontent.com/1922453/43494514-4fb8a7e4-9587-11e8-9d6f-79e2f2a5e99e.png)

**Comment by timmyc** [comment]
> It seems like filtering by product would handle most use cases and help with finding specific downloads. Is that enough for v1?

I agree that should be enough for a v1, and cc @LevinMedia since I think you pinged the wrong David above.

**Comment by LevinMedia** [comment]
Yep @justinshreve product name should suffice for now. Thanks!
