### ISSUE TITLE
Component: Table sorting should be done via API request

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#266]
See https://github.com/woocommerce/wc-admin/pull/251#issuecomment-409301677 – The table sorting currently only sorts the loaded data. We should instead query off to the API to fetch a new page of sorted data, to account for large datasets.

> The test api endpoint does have support for an orderby arg, so i think we are good to go there. 
> Also this would have the query arg added to the url in wc-admin, which will ensure a link will load the exact report as someone would like to see it.

[Note: Wait for a real endpoint before building this in]

**Comment by psealock** [comment]
This one has been addressed, closing
