### ISSUE TITLE
Reports: Hidden table columns should persist per user

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#272]
See https://github.com/woocommerce/wc-admin/pull/268#issuecomment-410036338

> Column toggles in legacy wp-admin views are persisted as, i'm guessing, a user preference between visits. Should we consider persisting column toggles on Woo Analytics reports too?

We can build off the user meta settings in #255 ?

**Comment by timmyc** [comment]
> We can build off the user meta settings in #255 ?

+1 seems like that would be a perfect use-case for this data.

**Comment by Aljullu** [comment]
This issue was fixed in #1057 and #1082.
