### ISSUE TITLE
Advanced Filter: UI translation audit

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#285]
Advanced Filters uses the order of English or LTR to convey what a filter is doing:

![screen shot 2018-08-09 at 12 21 31 pm](https://user-images.githubusercontent.com/1922453/43871045-ce69f802-9bce-11e8-8e67-aeb8c7fdf699.png)

and 

![screen shot 2018-08-09 at 12 21 40 pm](https://user-images.githubusercontent.com/1922453/43871049-d52a5510-9bce-11e8-81b4-750fbdbc1593.png)

How does this affect RTL languages? Is reversing the order using CSS sufficient in the second image? How can we effectively translate and present the first?

cc @ryelle 

parent issue: https://github.com/woocommerce/wc-admin/issues/256

**Comment by ryelle** [comment]
This isn't just an RTL issue, other LTR languages also use different word order – for example in Japanese we would want to say it in this order:

[Order status] __[pending dropdown]__ __[is/is not]__

**Comment by ryelle** [comment]
The other translation issue I've seen a few of us doing are things where we're patching together translated strings – like "Orders" patches into "%s Match" in your screenshot. Other languages will translate endings onto different words based on how they're used, so we should be passing as close to the finalized string as possible.
