### ISSUE TITLE
Component – Tables: Update style to match design

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#286]
[Invision mockup](https://automattic.invisionapp.com/share/4NN1HQC5B8F#/308750656_States)

Based on feedback https://github.com/woocommerce/wc-admin/pull/284#pullrequestreview-144875768

- Links should be purple and regular weight
- On that note, the entire row should act as a link. IE highlight on hover.
- Numerical cells (and column headings) should be justified right 

We'll want to take care with linking the entire row – the link content in the table row header will need to stay as-is, and we'll add a hover-style + onClick to the row. We should _not_ add a different aria role to the `tr`, as this breaks the table functionality. This also means we'll need to handle "mouse click on link" without firing the link action twice.

**Comment by LevinMedia** [comment]
Heya @ryelle the requirement for the whole row to be clickable is only going to be a requirement for the leaderboard tables on the dashboard - in the other tables the whole row will highlight on hover, but in many cases as you've pointed out, there will be multiple links in a row, each going to their own locations, so making the whole row clickable won't make sense. 

@jameskoster and I are  finalizing a dashboard master thread that will detail the aforementioned dashboard interaction.

**Comment by timmyc** [comment]
Since this does pose issues with a11y - is it worth the trade-off? It seems the link target of the product name in the Top Products example is plenty big enough of a touch target. Are there other reasons why we need the whole row click-able?

**Comment by LevinMedia** [comment]
It's more of a philosophical reason on the dashboard - Similar to what we discussed regarding charts on the dashboard: bigger hit area, less specific interactions, with the purpose of driving users deeper into the experience. 

You've got me thinking about it more though now - if the title is the only clickable thing in the row (and it's obviously clickable, because its styled as a link) do we need the rest of the row to be clickable too? Probably not. cc @jameskoster

**Comment by jameskoster** [comment]
I still think it would be nice to have. 

Possible compromise though; could we make the entire cell the link, instead of the row, without affecting a11y or requiring additional code?

**Comment by ryelle** [comment]
> Possible compromise though; could we make the entire cell the link, instead of the row, without affecting a11y

Yeah, we can adjust padding so the link takes over the entire cell, that's totally doable.

Moving @jameskoster's table feedback on #119 to this issue:

> Re table links, I think reports should behave just like all other links. We have some tables on the dashboard as well though; "Top selling products" etc. These are slightly different as the entire row should be the link. The hover style for the row should match the other tables as per p6riRB-3lZ-p2

I think we're all on the same page now -- links are links, and rows highlight on hover, but only the link cell is clickable.
