### ISSUE TITLE
Component Library

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#29]
One feature I enjoy in calypso is the ability to browse blocks from [devdocs](https://wpcalypso.wordpress.com/devdocs/design). Should we consider building our own component library with documentation/examples as we build out components for the Dashboard and Analytics?

This could serve as internal documentation for us, and eventually be a fantastic resource for 3PD who want to use design patterns from Dash/Analytics in their own extensions.

**Comment by belcherj** [comment]
@timmyc Should we revisit this as there are now more resources?

**Comment by timmyc** [comment]
It has shipped! When you have

```
define( 'WP_DEBUG', true );
define( 'SCRIPT_DEBUG', true );
```

in wp-config, you will see a link to the devdocs.
