### ISSUE TITLE
Component: EmptyState/EmptyContent

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/wc-admin#302]
Design: [inVision](https://automattic.invisionapp.com/d/main#/projects/prototypes/14707693).
Links: See p6riRB-3ja-p2. Calypso has some [prior art](https://wpcalypso.wordpress.com/devdocs/design/empty-content).

<img width="476" alt="screen shot 2018-08-16 at 9 33 59 am" src="https://user-images.githubusercontent.com/689165/44211666-87e4eb80-a137-11e8-925f-1fa12029ef6c.png">

A component is needed to display in instances where no data exists (no orders, etc).

**Comment by justinshreve** [comment]
Include an option to refresh/reload the page (so this can also be used for errors).

https://github.com/woocommerce/wc-admin/pull/299#issuecomment-413850288

**Comment by timmyc** [comment]
Closed by #348 I believe.
