### ISSUE TITLE
Filters can get "stuck" on previous pages/queries

### ISSUE THREAD

**Issue by ryelle** [woocommerce/wc-admin#305]
As of #297, filters aren't updating path + query correctly. Path & query seem to persist between pages.

- Go to the `Analytics > Products` page first, and update a filter. Then go to the `Analytics > Orders` page and update a filter. It loads the products path (with that filter).
- Go to `Analytics > Orders`, and click "show top orders by items sold". Then go to `Analytics > Products`, the filter on this page will still be set to "show top products by items sold".

This seems to be an issue with `history` not catching up, see https://github.com/woocommerce/wc-admin/pull/297#issuecomment-414403442

**Comment by timmyc** [comment]
Are we okay to close this one out now?

**Comment by ryelle** [comment]
Yep, should be fixed after #308.
