### ISSUE TITLE
Analytics: Client-Side CSV Download

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#312]
Child issue of #311 

This task involves implementing __Phase One__ detailed in the parent issue:

Phase one will implement the same approach that exists in both Calypso Stats and legacy WooCommerce reports, where data that is already present in the client will be exported. [Calypso CSV Download](https://github.com/Automattic/wp-calypso/tree/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/stats/stats-download-csv) is one implementation that can be used as prior art.

**Comment by ryelle** [comment]
@Aljullu Is this issue complete with the merge of #326?

**Comment by Aljullu** [comment]
Oh, yes. Closing it.

Thanks for noticing! @ryelle
