### ISSUE TITLE
Update Tool Tip in Graphs

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#373]
### Standard Graph (#458)

**Current tool tip:**
<img width="1464" alt="screen shot 2018-09-07 at 9 24 35 am" src="https://user-images.githubusercontent.com/4500952/45231776-11449500-b282-11e8-8cbf-5cc42c3ec920.png">

**Updated Tool Tip**
<img width="1466" alt="screen shot 2018-09-07 at 9 22 33 am" src="https://user-images.githubusercontent.com/4500952/45231785-1e618400-b282-11e8-85db-bbc34d4c939a.png">

- The title of the tool tip should display the data that is currently plotted in the graph
- The legend in the tool tip should display the specific dates the user is hovering over.

### Comparison Graph (#459)

**Current comparison tool tip:**
<img width="1715" alt="screen shot 2018-09-19 at 2 53 26 pm" src="https://user-images.githubusercontent.com/4500952/45783855-d9433780-bc1b-11e8-9a80-52d0bc27510c.png">

**Updated comparison tool tip**
<img width="1402" alt="screen shot 2018-09-19 at 2 53 01 pm" src="https://user-images.githubusercontent.com/4500952/45783891-efe98e80-bc1b-11e8-8a78-d056693ec306.png">

- The title of the tool tip should display the date in plain langauge

### Overflow and wrapping (#471)

There are still cases where the tool tip is wrapping within it's container, or overflowing the page, rather than repositioning to the inside of selected date.

<img width="1746" alt="screen shot 2018-09-19 at 2 58 25 pm" src="https://user-images.githubusercontent.com/4500952/45784116-828a2d80-bc1c-11e8-88b7-2002998e145e.png">

<img width="1733" alt="screen shot 2018-09-19 at 2 58 12 pm" src="https://user-images.githubusercontent.com/4500952/45784150-9897ee00-bc1c-11e8-82c3-3d0169c8717b.png">

**Comment by ryelle** [comment]
The contrast on that tooltip title (Gross Revenue in the updated design) should also be increased, right now it's only 1.9 (should be 4.5+). `$core-grey-dark-300` is the lightest grey that can be put against white for passing contrast.

**Comment by Aljullu** [comment]
@LevinMedia with #458, #459 and #471 being already merged, is it ok if I close this bug or is there something else missing?

**Comment by LevinMedia** [comment]
@Aljullu Looks good to me! I'll close it out. Thank you!
