### ISSUE TITLE
Define specific color stops for charts with five series or less

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#375]
Charts currently pull from the extreme ends of our color scale. For example, on a two series legend we have a dark purple and golden yellow. 

<img width="1448" alt="screen shot 2018-09-07 at 1 30 54 pm" src="https://user-images.githubusercontent.com/4500952/45241842-d69f2480-b2a2-11e8-89fe-be141a5cca36.png">

Using the following color stops will result in a less extreme color scale as the number of series progresses up to 5. After 5 series we can let math take over, creating an even scale with however many stops are required. 

The images below are based  the color scales [Viridis](https://github.com/d3/d3-scale-chromatic#interpolateViridis) and [Plasma](https://github.com/d3/d3-scale-chromatic#interpolatePlasma)

<img width="1995" alt="screen shot 2018-09-07 at 12 14 20 pm" src="https://user-images.githubusercontent.com/4500952/45240455-9c7f5400-b29d-11e8-9eaa-dc57cea86621.png">

**Comment by greenafrican** [comment]
Fixed in #381
