### ISSUE TITLE
Chart: X-Axis overflowing container

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#376]
To recreate: Use the revenue report - select a time frame with more than 12 days, the chart overflows the container to the left. 

<img width="1525" alt="screen shot 2018-09-07 at 1 41 42 pm" src="https://user-images.githubusercontent.com/4500952/45242556-55955c80-b2a5-11e8-9a43-0576e3946b19.png">

As a bi-product, the tool tip starts to misbehave (overflows off the side of the page) once the chart overflows the container:

<img width="1531" alt="screen shot 2018-09-07 at 1 47 20 pm" src="https://user-images.githubusercontent.com/4500952/45242581-73fb5800-b2a5-11e8-98a4-b9b863a18123.png">

**Comment by greenafrican** [comment]
Fixed in https://github.com/woocommerce/wc-admin/pull/381
