### ISSUE TITLE
Chart wont plot longer time period (4+ months)

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#384]
To recreate - select "year to date" from the date range picker. Note in the graph: data is only plotted through the 25th of April. 

<img width="1646" alt="screen shot 2018-09-10 at 9 28 41 am" src="https://user-images.githubusercontent.com/4500952/45310977-a17e1680-b4dc-11e8-86cd-ec3ee6910a0e.png">

Related to #382

**Comment by greenafrican** [comment]
@LevinMedia Is this off the `master` branch? I can't seem to replicate this.

**Comment by LevinMedia** [comment]
Affirmative.

**Comment by greenafrican** [comment]
<img width="815" alt="screenshot 2018-09-10 20 43 46" src="https://user-images.githubusercontent.com/1160732/45320126-0fa8f480-b542-11e8-8243-1eaed5e93bdd.png">

This isn't a chart issue. It seems as though the chart component only receives 100 results.

**Comment by justinshreve** [comment]
This is broken in master, but will be fixed as part of #483.
