### ISSUE TITLE
Revenue Report: Make Tabular data independent of Chart Interval

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#385]
From https://github.com/woocommerce/wc-admin/pull/359#issuecomment-420012931

>Changing the interval in the graph should not change the tabular data in the revenue report. Tabular data should always be listed out in rows by day. It's currently changing it to match the interval of the graph:

<img width="1623" alt="screen shot 2018-09-10 at 11 18 19 am" src="https://user-images.githubusercontent.com/4500952/45316224-53bcda80-b4eb-11e8-85c1-2bf68827046f.png">

**Comment by justinshreve** [comment]
@LevinMedia What about if the interval selected is `hour`? Should the table just list one row for the entire day, or would this be the exception? When I previously asked about this, it sounded like we wanted hours in the table: p1534527006000100-slack-woo-dash

**Comment by LevinMedia** [comment]
@justinshreve thanks for pointing that out, I missed that convo. That would be the the exception.
