### ISSUE TITLE
REST API: Zero Fill Stats Responses

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#402]
Copied from: https://github.com/woocommerce/woocommerce/issues/21298 moving over here as the development of this will likely take place in wc-admin instead of woo core.

---

To make life easier for front end teams and to prevent duplicating logic in mobile and JS side, we should bring back the fill in zeroes functionality for the reports endpoints. 

Probably the code removed in https://github.com/woocommerce/woocommerce/pull/20965 can be adapted back. There are probably some edge cases that might be not covered, plus tests needs to be written for the code.

**Comment by peterfabian** [comment]
I think this can now be closed, as #420  has been merged, if you agree?

**Comment by timmyc** [comment]
Yep, lets close it out, thanks @peterfabian 🙇
