### ISSUE TITLE
Chart Header: Add separator, fix vertical alignment

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#416]
Couple of small tweaks are still needed in the chart header area:

<img width="424" alt="current-chart" src="https://user-images.githubusercontent.com/22080/45591282-0c778500-b903-11e8-9aa7-886df195f1c5.png">

The Interval select seems to be a bit vertically off, looks like more space below than above ( or could just be me and my tired eyes ) - but we do need to add in the line separator between the interval drop-down and the chart toggles:

__Design__
![image](https://user-images.githubusercontent.com/22080/45591287-303acb00-b903-11e8-89c6-945991a79801.png)

Note #409 covers the ellipsis menu

**Comment by LevinMedia** [comment]
Thanks for making this issue @timmyc  - I think we should also address the behavior of these elements on a mobile device too, per the breakpoint documentation at p6riRB-3jq-p2

<img width="403" alt="screen shot 2018-09-19 at 3 41 34 pm" src="https://user-images.githubusercontent.com/4500952/45785817-9c2e7380-bc22-11e8-935f-645d18cd55cd.png">

**Comment by timmyc** [comment]
Likewise the in-between viewport width, things are a wee bit funky:

![image](https://user-images.githubusercontent.com/22080/45787411-0bf42c80-bc2a-11e8-9914-1b666655f023.png)
