### ISSUE TITLE
Orders Report: Table

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#418]
Child task of #168 
[inVision](https://automattic.invisionapp.com/d/main#/projects/prototypes/15060831)

This task involves creating the table from API data for the Orders Report:

![image](https://user-images.githubusercontent.com/22080/45591371-b2c48a00-b905-11e8-8fb6-6f4cf927c498.png)

We should be able to leverage work done on the Revenue Report to kick start this process. Note the "ViewMore" component still needs to be developed ( #415 ) so that can be skipped if it is not ready yet when this task is being worked on.

**Comment by timmyc** [comment]
Given we have a larger number of developers working on reports now, I think we should break out those tasks into distinct issues, child issues of this one. And since the first two are dependent on the API, it would be nice to get detailed issues around them so @peterfabian and @claudiosanches could look into adding support.

For now though we could work on this issue by adding in real data from the API to the table. We could omit customer type, and the link to the coupon report for the time being, but it would be nice to implement as much as we can in the table.

**Comment by timmyc** [comment]
wow sorry for my incorrect response above - i thought this was the issue for the Products Table 🤦‍♂️ - I agree we can close this out, and open up the child issues instead. I'll go ahead and do that now.

**Comment by Aljullu** [comment]
> wow sorry for my incorrect response above - i thought this was the issue for the Products Table man_facepalming - I agree we can close this out, and open up the child issues instead. I'll go ahead and do that now.

No problem! Thanks for creating the follow-up tickets! :+1:
