### ISSUE TITLE
REST API: Downloads reports endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/wc-admin#428]
Schema:

- https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads
- https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_files
- https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_stats

**Comment by timmyc** [comment]
Few more details:

P2: p7bje6-15q-p2
swagger: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_stats](get_reports_downloads_stats)

The [current download stats endpoint](https://github.com/woocommerce/wc-admin/blob/master/includes/api/class-wc-admin-rest-reports-downloads-stats-controller.php) is mostly placeholder logic.

This new endpoint is what will be queried to build out the chart on the Downloads Report page:

![image](https://user-images.githubusercontent.com/22080/48962482-631dc280-ef35-11e8-9108-08e93ade4a0b.png)

It is unclear to me if this endpoint requires a new reporting table to be built, or if it can use the existing tables that have already been implemented.

**Comment by timmyc** [comment]
Also as I mentioned in #915 - the table design is calling for us to display the product name attached to the downloaded file, along with the username that downloaded the file. The current API response is return the associated object ID's for those two pieces of data. Would there be an option for us to request extended product data as we built in other endpoints so we don't need to query 3 endpoints to build out one row of data in the table?
