### ISSUE TITLE
Tabular Data: Update download button to match design documentation

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#442]
Update the download button to match the documentation per p6riRB-3lZ-p2

**Currently:**

<img width="563" alt="screen shot 2018-09-18 at 1 10 51 pm" src="https://user-images.githubusercontent.com/4500952/45713587-4be0e400-bb44-11e8-8bd9-020b62e0868b.png">

**Design documentation:**

<img width="768" alt="screen shot 2018-09-18 at 1 12 17 pm" src="https://user-images.githubusercontent.com/4500952/45713657-7d59af80-bb44-11e8-8f2e-ac63ec8e2396.png">

**Comment by joshuatf** [comment]
It looks like the "cloud-download" icon is not currently available in dash-icons and they're considering retiring it - https://github.com/WordPress/gutenberg/pull/10552#issuecomment-429348184

What do you think @LevinMedia ?  Should we push to add the cloud-download icon or switch to an alternative?

Here's the current download option for reference - https://cloudup.com/cH8SR8Ki8v2

**Comment by LevinMedia** [comment]
Heya @joshuatf can we pull in gridicons here? http://automattic.github.io/gridicons/ The download cloud is available there too, but if that doesn't work, the icon you provided would work too.

**Comment by joshuatf** [comment]
> Heya @joshuatf can we pull in gridicons here? http://automattic.github.io/gridicons/ The download cloud is available there too, but if that doesn't work, the icon you provided would work too.

@LevinMedia The full set doesn't seem to be available in Gutenberg where we pull icons and I don't think we'll want to add another dependency.  But I'm sure we can add that single SVG path manually and include it inline.

**Comment by timmyc** [comment]
Closed by #560
