### ISSUE TITLE
Tabular Data: Update column alignment

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#444]
Per the design documentation at p6riRB-3lZ-p2 - the first (left most column) should be aligned left, the remaining columns should be aligned right.

<img width="1191" alt="screen shot 2018-09-18 at 2 20 51 pm" src="https://user-images.githubusercontent.com/4500952/45717215-193be900-bb4e-11e8-82d7-923c791eb448.png">

**Comment by joshuatf** [comment]
I believe this is solved by https://github.com/woocommerce/wc-admin/pull/493 @Aljullu can you confirm?

**Comment by Aljullu** [comment]
Yes, I think so. I will close this issue.

@LevinMedia feel free to open it again or create a new issue if you think this task is not finished.
