### ISSUE TITLE
Update default date range

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#455]
Update default date range: Month to Date vs. Previous Year

<img width="1016" alt="screen shot 2018-09-19 at 3 20 28 pm" src="https://user-images.githubusercontent.com/4500952/45785103-f67a0500-bc1f-11e8-87f3-d0ffecf42a39.png">

**Comment by LevinMedia** [comment]
This setting is based on feedback from the previous round of usability testing.

**Comment by gravnetic** [comment]
...also there should be a year to date range setting since every business works off of a unique caledar year for revenue.

**Comment by LevinMedia** [comment]
Heya @gravnetic thanks for your feedback! We do have a Year to date setting in the presets. Although, it runs off the calendar year, starting Jan 1. 

<img width="495" alt="Screen Shot 2019-04-07 at 8 47 58 PM" src="https://user-images.githubusercontent.com/4500952/55697601-f00e6900-5976-11e9-8b0c-d79c034a734f.png">

It sounds like what you're interested in is some sort of input in the analytics settings that allows you to set a specific fiscal year start date, like June 1st, correct? For example, 

Then if you were using setting in the screen shot above, it would calculate your year to date of June, 1st rather than Jan 1st.

**Comment by gravnetic** [comment]
Right, this is the specific feature that I am addressing, but Jan 1st is not how businesses work.

There needs to be an option where a business or website can set the calendar year.  This is how Metorik has it set up and it works brilliantly!

Thank you,


Jake Hawkes

Design | Develop | Motion

Hawkes.Design

208.867.8172<tel:+1-208-867-8172>

Simple, Effective Creative

________________________________

**Comment by psealock** [comment]
Thanks for bringing this to our attention @gravnetic. I created a separate issue to track this specifically so it won't get lost in this separate thread, https://github.com/woocommerce/woocommerce-admin/issues/2016

**Comment by gravnetic** [comment]
Has there been any further movement on this feature request?  I am loving the new admin so much!

**Comment by psealock** [comment]
Thanks for the feedback @gravnetic! No progress has been made in this regard, but I did see your other request for a persisted date setting, which is a great suggestion. I added that issue to our queue of tasks.
