### ISSUE TITLE
Add order_status column to lookup tables.

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/wc-admin#475]
To prevent unnecessary joining with `wp_posts` table each time, I think it would help to have `order_status` column in the lookup tables.

Also, think about how to make the UX working for selecting order statuses... should it be a setting somewhere or should it be an always visible JS UI element with pre-selected defaults?

**Comment by joshuatf** [comment]
@peterfabian Just to confirm and get a bit more context here, we're still planning on only allowing orders with a status of `completed`, `processing`, or `on-hold` to be stored in this table right?  Or is the plan to include all data, including that of refunded and cancelled orders?
