### ISSUE TITLE
Summary Number Layout

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#502]
As the viewport is scaled down, a bug is encountered at the 1000px breakpoint in the summary number. The layout breaks, aligning the summary numbers to the far left side of the screen, however the background of the container is still visible. At the 782px breakpoint, the rest of the components on the page jump to full width, however, the summary number maintains the margins on the edge of the page. The unselected summary numbers also remain visible. 

 Refreshing the page below the 1000px breakpoint produces the expected results. (Full width element, hides unselected summary numbers)

**Currently:**

<img width="855" alt="screen shot 2018-10-10 at 8 25 03 am" src="https://user-images.githubusercontent.com/4500952/46747458-3607a000-cc66-11e8-995b-f38a88f1b752.png">

**Expected:**

<img width="847" alt="screen shot 2018-10-10 at 8 25 16 am" src="https://user-images.githubusercontent.com/4500952/46747472-4455bc00-cc66-11e8-9841-28d5755bae51.png">

**Comment by belcherj** [comment]
The problem here is that we add classnames for the summary when it is first rendered and do not update them should the viewport change.  Watching the viewport for changes is not a great idea.

I think the way this works needs to be rethought if we would like for modifying width to work as you are expecting.

**Comment by belcherj** [comment]
I'm going un-assign for now as this is a larger task and not critical.

**Comment by joshuatf** [comment]
@LevinMedia This looks like it may have been resolved.  Can you test and let me know if you are still able to reproduce this issue?

**Comment by joshuatf** [comment]
Spoke with @LevinMedia on slack and confirmed that this issue is resolved.
