### ISSUE TITLE
Enhance line chart readability across viewport sizes

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#505]
As it stand, the line charts become quite hard to read as the viewport size decreases. 

**Current example: Viewport <728px**

<img width="379" alt="screen shot 2018-10-10 at 10 31 54 am" src="https://user-images.githubusercontent.com/4500952/46754709-f6e24a80-cc77-11e8-96aa-29d4910137a5.png">

The following updates aim to enhance line chart readability across viewport sizes by adjusting the chart aspect ratio, as well as the line weights and styling. The changes to the chart aspect ratios should also apply for bar charts. 

The height of the chart is currently defined on line 267 of `client/components/chart/index.js:267`

**Viewport >1329: 50 or less x axis ticks**

<img width="1504" alt="screen shot 2018-10-10 at 10 10 02 am" src="https://user-images.githubusercontent.com/4500952/46753439-b1704e00-cc74-11e8-9585-033f5f2696b6.png">

Height: 300
Dots
Line weight: 3

**Viewport >1329 50 or more x axis ticks**

<img width="1504" alt="screen shot 2018-10-10 at 10 01 15 am" src="https://user-images.githubusercontent.com/4500952/46753550-06ac5f80-cc75-11e8-9762-c282c2a7a951.png">

Height: 300
No dots
Line weight: 2

**Viewport 1329 - 783**

<img width="1091" alt="screen shot 2018-10-10 at 9 45 04 am" src="https://user-images.githubusercontent.com/4500952/46754297-f8f7d980-cc76-11e8-80e6-cf0383d6b29e.png">

Height: 220
No dots
Line weight: 2

**Viewport <783**

<img width="378" alt="screen shot 2018-10-10 at 9 42 40 am" src="https://user-images.githubusercontent.com/4500952/46754358-1c228900-cc77-11e8-98cb-23625fba4ff1.png">

Height: 180
No dots
Line weight: 1.5

**Comment by greenafrican** [comment]
@LevinMedia is the x-axis ticks breakpoint at 50 or 59?

> Viewport >1329: 59 or less x axis ticks

or 

> Viewport >1329 50 or more x axis ticks

**Comment by LevinMedia** [comment]
@greenafrican  / @joshuatf  should be 50. Sorry about that. Will update in the notes above.

**Comment by greenafrican** [comment]
@LevinMedia 

I've got a PR ready for this but wanted to get your thought on an example where the viewport is just below 1329 with only a week's worth of data showing:
![screenshot 2018-10-16 13 19 18](https://user-images.githubusercontent.com/1160732/47014115-93f62500-d149-11e8-8438-178e550108f8.png)

Would this (and even a few smaller viewports) not look better with dots?

**Comment by greenafrican** [comment]
@LevinMedia What do you think about using a ratio of width to x-values? My first pass is maybe if the `(viewport / points)` should be more than 50px. This would ensure at least 50px between each dot and feels like enough breathing room? We could make it more too if you prefer?

**Comment by joshuatf** [comment]
@greenafrican Sorry, didn't realize you were also working on this.  If your PR is ready I'll hold up on mine and assign this back to you.

**Comment by LevinMedia** [comment]
@greenafrican that might be an interesting approach... is that something I can check out in a branch to see how it works?
