### ISSUE TITLE
Add Utils to Exports/Global Namespace

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#508]
Currently we are making our wc-admin components available via the `@woocommerce/components` [and `wc.components`](https://github.com/woocommerce/wc-admin/blob/master/webpack.config.js#L7) which allows developers a route in which to consume and use them within their extensions.

While working on an example Report extension - I hit a few scenarios where having access to utility functions like [`formatCurrency`](https://github.com/woocommerce/wc-admin/blob/master/client/lib/currency/index.js#L15) [#](https://github.com/timmyc/wcs-example-report/blob/master/js/src/report.js#L142-L145)  and [`getCurrentDates`](https://github.com/woocommerce/wc-admin/blob/master/client/lib/date/index.js#L261-L284) [#](https://github.com/timmyc/wcs-example-report/blob/master/js/src/report.js#L63-L79) would have made my development a bit easier.

The pattern established in Gutenberg is to create new packages for this sort of functionality ( i.e. [`@wordpress/date`](https://github.com/WordPress/gutenberg/tree/master/packages/date) ) So I was wondering if we should follow that pattern, or consider having a more catch-all / generic `@woocommerce/utils` - either way being able to access these types of utils via a global or an import would really help extension developers work more efficiently against our project.

/cc @ryelle for your thoughts on this since you have worked quite a bit with the extensibility in the project thus far.

**Comment by ryelle** [comment]
>So I was wondering if we should follow that pattern, or consider having a more catch-all / generic `@woocommerce/utils`

I think we should follow the WP pattern, and have `@woocommerce/csv`, `@woocommerce/currency`, etc. Basically matching the `client/lib` folders to exports (and moving any `lib/*.js` files into folders to export if needed, like `ui`).

The exceptions would be…

- `lib/async-requests`: do we need to export this?
- `lib/nav-utils`: if we want to export this, we should rename the export; maybe just `wc.navigation`
- `lib/order-values`: I would also lean to renaming this, but maybe `wc.orderValues` is fine?
- `lib/tracks.js`: Is this for internal use only?
- `lib/history.js`, `lib/proptype-validator.js`: internal-only

We'll also want to move things to a lerna set up if we do this, which will help make the exported packages clear.

**Comment by timmyc** [comment]
Thanks for the feedback @ryelle - definitely sounds like a good plan.

> We'll also want to move things to a lerna set up if we do this, which will help make the exported packages clear.

Do you have any idea of the time/level of effort that is involved to do this? I've never personally worked with Lerna.
