### ISSUE TITLE
Revenue analytics shows retrieval error on initial load

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#528]
When initially loading up the Revenue reports on a local install, the page shows an error: 

<img width="1516" alt="revenue_error" src="https://user-images.githubusercontent.com/10561050/46967591-0221e580-d07f-11e8-8ce4-29ff41c9f31a.png">

## Error

`There was an error getting your stats. Please try again.` is shown on the Revenue page.  The network request shows:

`Invalid argument supplied for foreach() in <b>/Users/joshua/Code/wc-admin/includes/data-stores/class-wc-admin-reports-data-store.php</b> on line <b>304`

Looks like the `$interval` array passed to `cast_numbers()` is not set on the first pass.

## Steps to reproduce

I wasn't able to get this working on an online install, so here are some items this may be specific to:

* No order data was inserted.
* Not using a virtual host (relative path to WP install).

Visiting the Revenue page shows this issue immediately.

**Comment by belcherj** [comment]
You are getting the same error that I am getting on the Products report:  https://github.com/woocommerce/wc-admin/pull/548
