### ISSUE TITLE
Product Report: Chart & Summary Numbers

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#534]
Child task of #169 

**Design Post**: p6riRB-3dP-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats](get_reports_products_stats)

Invision: [Large Viewport](https://automattic.invisionapp.com/d/main#/console/15060831/313168864/preview) | [Mobile](https://automattic.invisionapp.com/d/main#/console/15060831/313951190/preview)

This issue involves adding the Summary Numbers and chart to the Products Report:

![image](https://user-images.githubusercontent.com/22080/46988284-c9990080-d0ac-11e8-8dbc-28f4d50a592f.png)

**Comment by LevinMedia** [comment]
Related - for the product detail screen, we'll also need to build out / include the comparison chart detailed at: p6riRB-3u4-p2

<img width="748" alt="screen shot 2018-10-17 at 12 31 59 pm" src="https://user-images.githubusercontent.com/4500952/47111552-b307bc00-d208-11e8-8bcb-e84cdd1e9f5c.png">

cc @greenafrican
