### ISSUE TITLE
Products Report: Add Table Filter

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#536]
Blocked by #535

Child task of #169 

**Design Post**: p6riRB-3dP-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats](get_reports_products_stats)

Invision: [Large Viewport](https://automattic.invisionapp.com/d/main#/console/15060831/313168864/preview) | [Mobile](https://automattic.invisionapp.com/d/main#/console/15060831/313951190/preview)

This task involves adding support to the Products Report table for the header filter:

![image](https://user-images.githubusercontent.com/22080/46988544-f4378900-d0ad-11e8-8399-16a97cde0417.png)

**Comment by psealock** [comment]
This was wrapped up by https://github.com/woocommerce/wc-admin/pull/495
