### ISSUE TITLE
Products Report: Add Comparison Filter

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#537]
Child task of #169 

**Design Post**: p6riRB-3dP-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_products_stats](get_reports_products_stats)

Invision: [Large Viewport](https://automattic.invisionapp.com/d/main#/console/15060831/313168864/preview) | [Mobile](https://automattic.invisionapp.com/d/main#/console/15060831/313951190/preview)

This issue involves adding the Comparison Filter to the Products Report:

![image](https://user-images.githubusercontent.com/22080/46988723-d3bbfe80-d0ae-11e8-803f-9743fb6af081.png)

**Comment by psealock** [comment]
This one is already done with Product Comparison and Product Category Comparison
