### ISSUE TITLE
Usage Tracking: Allow for other JS tracking services besides Tracks

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#555]
Presently, wc-admin/client/lib/tracks.js is tied directly to the Automattic Tracks global `window._tkq` which is injected by wc-admin/lib/client-assets.php ( https://github.com/woocommerce/wc-admin/blob/57c10ca866e9522564fc2c7e566eb4c3b3c753ef/lib/client-assets.php#L66 ) and referenced by wc-admin/client/lib/tracks.js

It would be good to allow 1) 3rd party devs to disable Tracks in the wc-admin/WooCommerce context and 2) substitute in their own service if desired.

We could 1) wrap and action hook the PHP enqueueing code and 2) allow 3rd parties to register their own function to use in lieu of our recordEvent.

**Comment by timmyc** [comment]
Closing this as out of scope for this project, but likely to be picked up in Woo Core in Q1
