### ISSUE TITLE
Usage Tracking: Update Usage Tracking Doc, Disclose Tracks to Users

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#556]
The WooCommerce Setup Wizard Usage tracking prompt (to see it on an existing install, first reset it by going to wp-admin > Status > Tools and clicking on Reset under Reset Usage Tracking and then go to wp-admin/admin.php?page=wc-setup ) currently reads:

> Help WooCommerce improve with usage tracking.

> Gathering usage data allows us to make WooCommerce better — your store will be considered as we evaluate new features, judge the quality of an update, or determine if an improvement makes sense. If you would rather opt-out, and do not check this box, we will not know this store exists and we will not collect any usage data. Read more about what we collect.

The last sentence links to https://woocommerce.com/usage-tracking/

We should:

- [ ] Update https://woocommerce.com/usage-tracking/ to reflect Tracks behaviors
- [ ] Come up with a way to prompt existing users that checked the box to be re-prompted when updating to whatever version of WooCommerce wc-admin is eventually included in

**Comment by timmyc** [comment]
Closing this as out of scope for this project but will likely be handled as part of a larger Woo core effort in Q1
