### ISSUE TITLE
REST API: Additional Footer Data needed in Order Stats

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#559]
Follow up task from #418

As @Aljullu mentioned in the prior issue:

> values used in the footer of the table are not returned by the API yet, either.

Currently the footer in the orders report looks like:

![image](https://user-images.githubusercontent.com/22080/47117573-9627b480-d219-11e8-9d82-1830cf1446a7.png)

And the design calls for a summary data set akin to what we show in the Revenue Report:

![image](https://user-images.githubusercontent.com/22080/47117606-ab9cde80-d219-11e8-8dba-fd48344b1228.png)

/cc @claudiosanches @peterfabian

**Comment by joshuatf** [comment]
@LevinMedia Just to double check: the products figure here is meant to be unique products sold in that period, right?

**Comment by LevinMedia** [comment]
@joshuatf - affirmative. Unique products.

**Comment by LevinMedia** [comment]
For reference - here's the footer data behavior on a mobile device: 

<img width="426" alt="screen shot 2018-10-22 at 8 19 50 am" src="https://user-images.githubusercontent.com/4500952/47301262-5bd06580-d5d3-11e8-9941-150d2137543f.png">
