### ISSUE TITLE
Chart with empty data set

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#582]
If dates are selected on the Product Reports chart with no order history, an emtpy chart is shown.  This may be confusing or look broken to users.

<img width="1113" alt="screen shot 2018-10-18 at 4 49 57 pm" src="https://user-images.githubusercontent.com/10561050/47183808-00625700-d2f7-11e8-860f-85a4c720c30d.png">

#### Options

Should we:

* Show a message or something here?  E.g., "There is no data for your selected range."
* Hide the chart
* Something else?

#### Additional context
Depends on empty product data returned from API - #581

**Comment by LevinMedia** [comment]
Hi Josh, this is part of a larger "empty states" issue I need to address.  

For the time being I'll repurpose an SVG image file we can include to indicate that there is no data for the selected time period.

**Comment by timmyc** [comment]
@LevinMedia do you have time at all next week to get a design for the empty state on the charts? I'd like to get this into sprint 11

**Comment by LevinMedia** [comment]
@joshuatf @timmyc  Did some fiddling with empty states this afternoon... we're not that far off. Here's what I was thinking: 

<img width="1380" alt="screen shot 2019-01-30 at 8 05 39 pm" src="https://user-images.githubusercontent.com/4500952/52029986-91d28f00-24ca-11e9-9a81-538cd0029ecc.png">

- Always show every series in the legend (both standard charts and comparison charts) with their values being 0, or $0 depending on if the value is a number or a currency. 
- Remove the values from the Y-axis ticks except for the baseline. 
- The baseline should read 0, or $0 depending on if the value is a number or currency. 
- The x-axis should always show the ticks according to the date range selected. 
- If the chart is in line chart mode, it should flatline across the bottom of the chart.
- If the chart is in bar chart mode, it should be blank
- in the middle of the chart, display the message "No data for the selected date range" 
- The text should wrap to two lines and maintain it's position (centered vertically) on smaller viewports
`font-size:18px;`
`line-height:27px` 
`font-weight: bold;`
`color: light-grey-700`

**Comment by timmyc** [comment]
Thanks @LevinMedia !
