### ISSUE TITLE
Changing chart interval on orders, or product report always switches back to revenue report

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#663]
to reproduce: 

On master, navigate to the orders report
Change the chart interval from day to week
Note the report reloads as the revenue report, with the selected chart interval applied.

![screen recording 2018-10-23 at 06 49 pm](https://user-images.githubusercontent.com/4500952/47401151-fd9ba380-d6f4-11e8-91a9-d2e334298cb1.gif)

**Comment by belcherj** [comment]
Dupe:  https://github.com/woocommerce/wc-admin/issues/704

**Comment by belcherj** [comment]
I am not able to replicate.

**Comment by Aljullu** [comment]
@belcherj

> I am not able to replicate.

Right, the fix from #717 was needed to replicate this issue.

I will assign this issue to myself, if that's ok for you! :slightly_smiling_face:
