### ISSUE TITLE
Compare Filter: UI Improvements

### ISSUE THREAD

**Issue by psealock** [woocommerce/wc-admin#682]
When comparing products, the compare button could use improvements:

1. When clicking "Compare" query parameters from the previous filter should be cleared out
2. The "Compare" button should be disabled when the current selection is already represented in the url.

![screen shot 2018-10-25 at 12 44 54 pm](https://user-images.githubusercontent.com/1922453/47467666-11a9e700-d854-11e8-8279-5b2ce7acea0c.png)

**Comment by ryelle** [comment]
> The "Compare" button should be disabled when the current selection is already represented in the url.

Why? We say "select at least two products to compare", and then show the currently selected items in the filter. If the button is disabled now (ex, in your screenshot), that text is confusing (two items _are_ selected). Does it matter that the button doesn't do anything when clicked?

**Comment by psealock** [comment]
>Does it matter that the button doesn't do anything when clicked?

When using the UI, it felt odd to me that clicking an action button did nothing and I had to think about why that might be. The Compare UI can be in the exact state shown in my screen shot, but the report can be in two different states (filtered, not filtered). I thought it would be a nice way to indicate the comparison has already been applied.

I see what you're saying about the text, however. We could change the text to match the context. @LevinMedia what do you think?

**Comment by LevinMedia** [comment]
I think the biggest affordance to whether or not the comparison has been applied or not hasn't actually been implemented into this report yet. That is... once the comparison is made (a user clicks on the comparison button), the graph will switch to the comparison version with the compared data points in in the legend (per https://github.com/woocommerce/wc-admin/issues/695 ) Additionally, once a comparison is made, the tabular data and summary numbers will update to only include what's being compared. 

One more thing we could do to clarify things: The "Clear All" link is always visible - I think it would be good to hide that until a comparison is made. Clicking "clear all" would return the report back to it's original state, and the clear all link would disappear. How's that sound?

**Comment by Aljullu** [comment]
@psealock I'm not sure to understand this point:
> When clicking "Compare" query parameters from the previous filter should be cleared out

Isn't that already happening?

**Comment by psealock** [comment]
>Isn't that already happening?

Hmm, I can't reproduce what I was referring to. So, yes.

Thanks for the explanation @LevinMedia. https://github.com/woocommerce/wc-admin/pull/736 fixes this issue then.
