### ISSUE TITLE
WSOD: Syntax error for T_OBJECT_OPERATOR (two instances)

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#691]
**Describe the bug**

My site runs PHP 5.6.36 (but I think object operators are a PHP 5.6 and higher thing, so shrug)

```
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /home/allsno1/allensnook.com/wp-content/plugins/wc-admin/includes/data-stores/class-wc-admin-reports-data-store.php on line 392
```

Also happens for line 402.

**To Reproduce**

1. Install and activate the plugin (using branch of master from earlier today)
2. See error and nothing else

**Comment by peterfabian** [comment]
Thanks for reporting. Please check if https://github.com/woocommerce/wc-admin/pull/702 fixes the issue.
