### ISSUE TITLE
Bug: switching intervals switches between analytics pages

### ISSUE THREAD

**Issue by greenafrican** [woocommerce/wc-admin#704]
**Describe the bug**
When changing intervals in the chart, I noticed that the entire page changed from the revenue report to the product report.

**To Reproduce**

1. Go to the revenue report, change the interval to 'by week'
2. Go to products report
3. Select product comparison and 3 products
4. Go back to revenue report and change interval to 'by week'
5. You get taken to the product comparison page

**Expected behavior**
Stay on the revenue report and change the interval to 'by week'

**Screenshots**
![change](https://user-images.githubusercontent.com/1160732/47566387-df6bb880-d92b-11e8-8cd3-4d454d10e6cf.gif)

**Desktop (please complete the following information):**

* OS: MacOS 10.13.6 
* Browser: Chrome 
* Version 69.0.3497.100

**Additional context**

**Comment by belcherj** [comment]
Dupe?  https://github.com/woocommerce/wc-admin/issues/663

**Comment by belcherj** [comment]
I am not able to replicate.

**Comment by Aljullu** [comment]
Closing since it should have been fixed by #731.
