### ISSUE TITLE
Activity Panel: Inbox won't open on non Dashboard, non Analytics routes

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#726]
**Describe the bug**

Clicking on the Activity Panel Inbox icon on pages other than the dashboard ( wp-admin/admin.php?page=wc-admin#/ ) or one of the analytics pages results in console errors and not much else.

```
Uncaught TypeError: Cannot read property 'getNotes' of undefined
    at inbox.js:92
```

**To Reproduce**

1. Go to a page like wp-admin > Woocommerce > Extensions > Subscriptions
2. Click on the Inbox

**Expected behavior**
The inbox should open and display its contents.

Props @belcherj for finding this.

**Comment by bor0** [comment]
I got this issue while tackling https://github.com/woocommerce/woocommerce-bookings/issues/1786. Not sure about reproduction steps. Is there a workaround?
