### ISSUE TITLE
Unable to add tax rates when WC-Admin is active

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#738]
**Describe the bug**
When WC-Admin is active, a user is unable to add tax rates to their store

**To Reproduce**

1. Ensure WC-Admin is active
2. Navigate to Settings>Taxes>Standard Tax rates 
3. Click the "insert row"
4. Note nothing happens
5. Same behavior is encountered in all other tax types ie: reduced rates, zero rates, and custom rates

**Expected behavior**
Clicking insert row should add a new row to the table per this screen shot:

<img width="1210" alt="screen shot 2018-10-30 at 12 42 15 pm" src="https://user-images.githubusercontent.com/4500952/47745779-b0ae5480-dc41-11e8-8c5b-cf0dcf3aa450.png">

After disabling WC-Admin, I was able to add tax rates as expected.

**Comment by peterfabian** [comment]
Hi, I wasn't able to reproduce the problem. I initially thought this might be a PHP bug, but I see now that the add row is handled by JS code, so maybe some error that is gone now?

**Comment by LevinMedia** [comment]
Heya @peterfabian Ah, yes, see version info below... I just checked again, and I still can't add it. 

WooCommerce: 3.5.1
WordPress: 4.9.8

When I click the insert row button console is throwing this error:

```settings-views-html-settings-tax.min.js?ver=3.5.1:1 Uncaught TypeError: _.indexBy is not a function
    at HTMLAnchorElement.onAddNewRow (settings-views-html-settings-tax.min.js?ver=3.5.1:1)
    at HTMLAnchorElement.dispatch (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:3)
    at HTMLAnchorElement.r.handle (load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:3)
onAddNewRow @ settings-views-html-settings-tax.min.js?ver=3.5.1:1
dispatch @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:3
r.handle @ load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery-ui-mouse,jquery-ui-sortable&ver=4.9.8:3```

**Comment by timmyc** [comment]
I can reproduce the issue too - looking like it might be a lodash conflict
