### ISSUE TITLE
REST API: Add Support for Sorting Reports/Products By Product Name

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#740]
This issue was brought up during work on #631 - the desired feature is to be able to sort requests to `/wc/v3/reports/products?orderby=` product name. The current supported fields for `orderBy` are `date, items_sold, gross_revenue, orders_count`

/cc @peterfabian do you think adding support for sorting by product name is doable, or was there a reason it was not supported in the initial build?

**Comment by peterfabian** [comment]
As product name originally wasn't part of the response, it kind of didn't make sense to sort by it. Now that we added extended_info switch, we can add it.
