### ISSUE TITLE
Add actions for tracking changes to wc-admin tables

### ISSUE THREAD

**Issue by thingalon** [woocommerce/wc-admin#754]
Jetpack Sync and Rewind need to track all of Woocommerce's custom tables to provide reliable live backups. We need WordPress actions that we can hook into which let us know that data has changed.

Can we please have some actions added to wc-admin to allow us to follow changes on the new tables:
```
{$wpdb->prefix}wc_order_stats
{$wpdb->prefix}wc_order_product_lookup
{$wpdb->prefix}wc_order_tax_lookup
{$wpdb->prefix}wc_order_coupon_lookup
{$wpdb->prefix}woocommerce_admin_notes
{$wpdb->prefix}woocommerce_admin_note_actions
{$wpdb->prefix}wc_customer_lookup
```

This is important as a part of supporting the WordPress.com eCommerce plan that is slated for release in mid-November.

For context: https://teamisotope.wordpress.com/2018/10/29/rewind-for-woocommerce-tables-and-events/

**Comment by timmyc** [comment]
Added `{$wpdb->prefix}wc_customer_lookup` to the list above.
