### ISSUE TITLE
WC-ADMIN should not require Gutenberg plugin to be active for WordPress 5.0 and higher

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#772]
**Describe the bug**

Attempting to activate the wc-admin plugin on a site running WordPress 5 ( 5.0-beta2-43859 )and WooCommerce (3.5.1) fails because even though Gutenberg is present in WordPress 5, our logic doesn't recognize it.

**To Reproduce**

1. Install a WordPress 5 beta (e.g. 5.0-beta2-43859 )
2. The Gutenberg plugin should be automatically disabled as a result.
3. Attempt to activate wc-admin plugin
4. See admin notice that Gutenberg is required

**Expected behavior**

wc-admin should activate on WordPress 5.0 without requiring Gutenberg

**Screenshots**

<img width="1362" alt="screen shot 2018-11-04 at 5 45 33 pm" src="https://user-images.githubusercontent.com/1595739/47970943-e4321a00-e059-11e8-90a9-aef14c0d6cf1.png">

**Comment by timmyc** [comment]
That would make sense why I wasn't seeing this on my test site as I'm not running 5.0
