### ISSUE TITLE
Navigation: Increase text/background contrast to improve accessibility

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/wc-admin#7815]
### Problem to solve
The existing text color for the new navigation doesn't pass AAA accessibility guidelines.
<img width="227" alt="Screen Shot 2021-10-18 at 12 25 20 PM" src="https://user-images.githubusercontent.com/5121465/137772803-86ba91e0-e3d9-4cbd-aa1a-d4007ca06d57.png">

<img width="1168" alt="Screen Shot 2021-10-18 at 12 27 24 PM" src="https://user-images.githubusercontent.com/5121465/137772583-10632584-8eb8-471b-83eb-1d0218018280.png">

### Proposed solution 
As discussed in pbIJXs-10, we should lighten the text color to `$gray-400` for all navigation links and update the hover state to `$white`.
This proposed update will pass all accessibility guidelines.
<img width="1058" alt="Screen Shot 2021-10-18 at 12 39 49 PM" src="https://user-images.githubusercontent.com/5121465/137772920-5e2e26d7-6436-43b3-923d-d672121f9040.png">

<img width="1168" alt="Screen Shot 2021-10-18 at 12 28 47 PM" src="https://user-images.githubusercontent.com/5121465/137772758-77797e93-752f-44f1-a8ef-9c67e0f8a21a.png">

**Comment by pmcpinto** [comment]
@becdetat @mattsherman we should also include this change in the cycle 18 scope.

**Comment by mattsherman** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Mothra-60df2bf941ae44000ebbda7c/issues/woocommerce/woocommerce-admin/7815?planning-poker) with ZenHub @jacob-sewell @joelclimbsthings @joshuatf @louwie17 @octaedro
