### ISSUE TITLE
Activity Panel: Inbox: wpdb::prepare was called incorrectly (on updating a note)

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#786]
**Describe the bug**

If you attempt to update a note, we attempt to call wpdb::prepare with a WC_DateTime instead of a string for the date_created (and date_reminder)

**To Reproduce**

1. WP_DEBUG true
2. Install the second of the two activity panel inbox sample plugins ( https://github.com/woocommerce/wc-admin/blob/master/docs/examples/activity-panel-inbox.md )
3. Activate it

**Expected behavior**

Expected no errors.

**Comment by joshuatf** [comment]
This appears to be resolved by https://github.com/woocommerce/wc-admin/pull/693 - @timmyc Can you replicate the issue?

**Comment by timmyc** [comment]
Indeed I can no longer reproduce the bug.
