### ISSUE TITLE
Add Support for Transient Notifications

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#806]
**Is your feature request related to a problem? Please describe.**

Iinbox notifications are intended for prompting the user of things like:
– they have a new best sales in a day record
– they have an expiring (or expired) woo extension subscription
– they haven’t set up something that wasn’t ever set up before
– content that could help with the day to day tasks of managing and optimizing a store

And Store Alerts are intended for
– shipping is enabled, but there are no shipping methods in any shipping zones
– things that had been working but are now not working (e.g. API key no longer valid)
– version and/or security updates

But some of our existing admin notices don’t seem to fit well into either category, e.g.:

<img width="644" alt="screen shot 2018-11-08 at 4 30 09 pm" src="https://user-images.githubusercontent.com/1595739/48268323-a5f27d00-e402-11e8-9de9-05579fe8deac.png">

In this particular example, the store manager updated the status on two bookings – @laurendavissmith  pointed this one out to me today.

**Describe the solution you'd like**

@LevinMedia wrote:

> sounds like a transient notification – we’ve done something similar with woocommerce services. Can we take the same approach there? Per our IRL convo, let’s try sliding it in on the bottom right corner of the screen

p90Yrv-S3-p2

I also discussed this briefly with @ryelle - we'll want to ensure the solution is an accessible one

**Should this be prioritized? Why?**

Let's prioritize this immediately after Store Alerts, that way extension developers will then have the tools to be able to cover all three kinds of notices.

**Comment by timmyc** [comment]
Since we have our first use case where this could be leveraged in #1364 seems like it is a good time to get this in.
