### ISSUE TITLE
Selecting a product in a table search box shouldn't trigger the comparison immediately

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#825]
Having this table:
![image](https://user-images.githubusercontent.com/3616980/48384294-600e1100-e6af-11e8-98da-c1146e8516a0.png)
Imagine we want to compare `doloremque` and `sint voluptas`.

We start writing `dolor` in the search field so the suggestions appear.
![image](https://user-images.githubusercontent.com/3616980/48384359-a9f6f700-e6af-11e8-9ec1-087e60982b4e.png)

When clicking on the first suggestion (`doloremque`) the comparison is immediately triggered hiding all other elements from the table.
![image](https://user-images.githubusercontent.com/3616980/48384389-c4c96b80-e6af-11e8-916c-100f9e18ba37.png)

I think clicking on a suggestion result should ONLY select the table item without triggering the comparison automatically so the table would still render the other results.

**Comment by psealock** [comment]
Related: https://github.com/woocommerce/wc-admin/pull/823 fixes some properties in config that caused unexpected behavior, ie `product` => `products`. 

I'm just noting in case you come across some oddities, even though this fix doesn't solve this issue here.

**Comment by Aljullu** [comment]
DIscussing with @LevinMedia it looks like this is not the implementation we want for the search box in tables, so I will close this issue.
