### ISSUE TITLE
Search suggestions don't work for multi-word entries

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#827]
If I have a product named `sit nihil iusto id sed` and I search for `sit n` in the _Single product_ filter of the _Product_ report, I would expect it to appear in the suggestions, but it currently doesn't.

![image](https://user-images.githubusercontent.com/3616980/48388324-7d96a700-e6be-11e8-9e8e-38ecf115f62b.png)

![image](https://user-images.githubusercontent.com/3616980/48388341-8e471d00-e6be-11e8-972a-741f6bc027a1.png)

**Comment by Aljullu** [comment]
After doing some research, I would say this is an API bug.

This request `/wc/v3/products&search=qui%20i` returns an empty array even though there is a product named `qui ipsum mollitia`.

In the other hand, `/wc/v3/products&search=qui` and `/wc/v3/products&search=qui%20` correctly return that result.

**Comment by peterfabian** [comment]
Hi @Aljullu, I can't seem to replicate this problem:
<img width="764" alt="2_word_2" src="https://user-images.githubusercontent.com/2207451/49163654-e4a69380-f32d-11e8-8c91-a0456505b02d.png">


When looking at the code, the REST API is using WP standard WP_Query class which translates the search query 'qui%20i' to roughly this in SQL:
```
AND 
 (
     (
         (wp_posts.post_title LIKE '%qui%') 
         OR (wp_posts.post_excerpt LIKE '%qui%') 
         OR (wp_posts.post_content LIKE '%qui%')
    ) 
    AND 
    (
        (wp_posts.post_title LIKE '%i%') 
        OR (wp_posts.post_excerpt LIKE '%i%') 
        OR (wp_posts.post_content LIKE '%i%')
    )
)

```
...so it should include products with name `qui ipsum mollitia`.
