### ISSUE TITLE
REST API doesn't return variations if the search parameter has more than one letter

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#831]
Consider we have a product variation named `unde sed`.

---

`/wc/v3/products/12/variations&search=u&per_page=10`

Returns that (and maybe more) results.

![image](https://user-images.githubusercontent.com/3616980/48419319-3db2dc80-e71d-11e8-94a6-6b84907ae4b9.png)

![image](https://user-images.githubusercontent.com/3616980/48419300-3095ed80-e71d-11e8-963b-081d81654a35.png)

---

`/wc/v3/products/12/variations&search=un&per_page=10`

Returns no results.

![image](https://user-images.githubusercontent.com/3616980/48419241-0ba17a80-e71d-11e8-86a9-ed1aed350c38.png)

![image](https://user-images.githubusercontent.com/3616980/48419255-178d3c80-e71d-11e8-9f72-cf737b0b4db9.png)

_Expected result:_ the second query should still return `unde sed` variation.

**Comment by peterfabian** [comment]
I think this only works if the variation does not have too many attributes or long name of attributes.
Based on function `WC_Product_Variation_Data_Store_CPT::generate_product_title`, it seems that if there are more than 2 attributes or multiple attributes with 2+ words, then the variation's title is not set to include variation's attribute values.

(Additionally, the search also does not search through variation description, which is stored as post meta.)

Proposed fix is to store attribute values to post_excerpt, then it should work fine, without the need to perform `JOIN` for each attribute: https://github.com/woocommerce/woocommerce/pull/22083.
