### ISSUE TITLE
REST API: Implement `reports/taxes` and `reports/taxes/stats` endpoints

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#844]
Currently the REST API reporting endpoints for taxes are using `WC_Reports_Orders_Stats_Query` with a `todo` to swap out the correct class name. In order to fully implement the reports, we both of the taxes endpoints fully developed.

Planning Post on Proton: p7bje6-15p-p2

**Comment by Aljullu** [comment]
According to the design post (p6riRB-3dT-p2), the swaggerhub examples should be updated:
- `reports/taxes` should include the the _rate_ for each tax code.
- `reports/taxes/stats` should include the _total number of tax codes_.

**Comment by peterfabian** [comment]
Hi @Aljullu, the rate can be fetched from existing endpoint, as described here: p7bje6-15p-p2. If we decide to include it in `/reports/taxes`, then we can update.
Should the total number of tax codes include all tax codes or only those used in the selected time period/subset of orders?

**Comment by joshuatf** [comment]
@peterfabian Is it possible to add in a query param for `tax_rate_id` to both the `/reports/taxes/stats` and `/reports/taxes` routes?  We'll probably need that for filtering unless we opt to do that client-side.

**Comment by joshuatf** [comment]
Closed via #1019 and #1000.
