### ISSUE TITLE
Component: Sparkline

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#85]
Child task of #82

**UPDATE**
The sparkline component is no longer being shown in the latest designs for dashboard blocks. As such I'm going to remove this from the backlog for now - and lets not work on this for the time-being.

------------------

Based upon the latest designs in p6riRB-3aN-p2 - each performance tile will include a Sparkline that will display the trend of data for the given stat:

![tile](https://user-images.githubusercontent.com/22080/40442290-0a6b59fc-5e78-11e8-822c-4068d3ad7bbd.png)

Ideally it would be nice to leverage the existing [Sparkline component from calypso](https://github.com/Automattic/wp-calypso/tree/master/client/extensions/woocommerce/components/d3/sparkline), and I'm going to chat with @psealock around some ideas of how we can best bring over the prior art to use here.

**Comment by belcherj** [comment]
@LevinMedia Can we close?
