### ISSUE TITLE
Additional payments task is shown when set up payments is displayed in main task list

### ISSUE THREAD

**Issue by louwie17** [woocommerce/wc-admin#8505]
### Describe the bug
Additional payments task is shown when set up payments is displayed in main task list

### To Reproduce

1. Install WooCommerce Admin 3.3 rc.2
2. Finish the onboarding but don't select any of the free features
3. Once redirected to home screen notice how `Add my payments` is shown in the main task list and the extended task list shows `Set up additional payment providers`

### Screenshots
<img width="869" alt="Screen Shot 2022-03-24 at 9 35 06 AM" src="https://user-images.githubusercontent.com/2240960/159917784-b6525e73-71ae-42db-bc12-c33b0425093b.png">

### Expected behavior
Only the `Add my payments` task should be shown not the `Set up addtional payment providers`

### Additional context

See proposed fix here in the `woocommerce` repo -> https://github.com/woocommerce/woocommerce/blob/76b9177539c37ec3d3699a2dfd4f8d8291f18962/plugins/woocommerce/src/Admin/Features/OnboardingTasks/Tasks/AdditionalPayments.php#L76-L79
We should be able to make the same change.

Please make sure the previous logic won't be affected as listed [here](https://github.com/woocommerce/woocommerce-admin/pull/8391), when WooCommerce Payments is selected in the free features.

**Comment by octaedro** [comment]
Cherry-picked to 3.3.0
