### ISSUE TITLE
Dependency on unsupported version of pnpm

### ISSUE THREAD

**Issue by tombola** [woocommerce/wc-admin#8527]
### To Reproduce
`brew install pnpm`
`pnpm install`

### Actual behavior:

```
➜ pnpm install
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your pnpm version is incompatible with "/Users/tom/DevKinsta/public/vitalseedscouk/wp-content/plugins/woocommerce-admin".

Expected version: ^6.24.2
Got: 7.1.7

This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.

To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
```

### Additional context
I came to this extension/plugin from this article: https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/

**Comment by tombola** [comment]
@psealock Is the [source article](https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/) outdated/deprecated btw?

**Comment by StasPonomaryov** [comment]
> @psealock Is the [source article](https://developer.woocommerce.com/2020/02/20/extending-wc-admin-reports/) outdated/deprecated btw?

I think it is. I got an error using that article (on step `npm run create-wc-extension`):
```Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: D:\OSPanel\domains\foodzy\wp-content\plugins\woocommerce-admin\node_modules\.pnpm\chalk@5.0.1\node_modules\chalk\source\index.js
require() of ES modules is not supported.
require() of D:\OSPanel\domains\foodzy\wp-content\plugins\woocommerce-admin\node_modules\.pnpm\chalk@5.0.1\node_modules\chalk\source\index.js from D:\OSPanel\domains\foodzy\wp-content\plugins\woocommerce-admin\bin\starter-pack\starter-pack.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines 
all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from D:\OSPanel\domains\foodzy\wp-content\plugins\woocommerce-admin\node_modules\.pnpm\chalk@5.0.1\node_modules\chalk\package.json.```

**Comment by ObliviousHarmony** [comment]
Hello @tombola, the code in `woocommerce/woocommerce-admin` has been migrated into `woocommerce/woocommerce`. You are still likely to experience that problem there and should downgrade your `pnpm` to 6.x. We have an open issue to upgrade it and it's in our backlog, but, we're currently migrating some other things at the moment.

Thanks!
