### ISSUE TITLE
Anayltics: Orders: Javascript Warning when no orders: Received NaN for the `children` attribute

### ISSUE THREAD

**Issue by allendav** [woocommerce/wc-admin#855]
**Describe the bug**

If there are no orders, the following is logged to the console when looking at wp-admin > Analytics > Orders

```
react-dom.24169eaf.js:526 Warning: Received NaN for the `children` attribute. If this is expected, cast the value to a string.
    in span (created by SummaryNumber)
    in span (created by SummaryNumber)
    in a (created by Link)
    in Link (created by Link)
    in Link (created by SummaryNumber)
    in li (created by SummaryNumber)
    in SummaryNumber (created by ReportSummary)
    in ul (created by SummaryList)
    in div (created by t)
    in t (created by ForwardRef(NavigableContainer))
    in SummaryList (created by r)
    in r
    in WithViewportMatch(SummaryList) (created by ReportSummary)
    in ReportSummary (created by r)
    in r
    in WithSelect(ReportSummary) (created by OrdersReport)
```

**To Reproduce**

1. Move any orders to the trash
2. Rebuild reports (wp-admin > WooCommerce > Status > Tools > Rebuild Reports)
3. Navigate to wp-admin > Analytics > Orders
4. See error in dev console

**Expected behavior**

No error

**Screenshots**

<img width="1438" alt="screen shot 2018-11-14 at 4 51 53 pm" src="https://user-images.githubusercontent.com/1595739/48522472-a9846a80-e82d-11e8-840c-0f12a54eb514.png">

**Desktop (please complete the following information):**

WP 4.9.8
Gutenberg 4.3

**Comment by joshuatf** [comment]
I think this issue may be resolved as I'm no longer able to reproduce.  @timmyc Are you able to reproduce this bug?
