### ISSUE TITLE
Analytics: Enhancements to Rebuild Reports Tool

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#860]
Currently the process to Rebuild, or populate the reporting tables for the first time, is a manually triggered process accessed via the "Tools" tab within the Status page. When that tool is launched, the [following logic](https://github.com/woocommerce/wc-admin/blob/501244778606bc7ec18433a26128efd4481ba966/includes/api/class-wc-admin-rest-system-status-tools-controller.php#L56-L60) calls [queue_order_stats_repopulate_database](https://github.com/woocommerce/wc-admin/blob/09d15f6a264561117c89aa9343ffc11c2e0007f6/includes/data-stores/class-wc-admin-reports-orders-data-store.php#L394) - which as it states in a TODO, needs to be reworked since it currently grabs *all* orders to process at once.

So I'm creating this issue to track that TODO and a few other potential enhancements:

- [ ] Update `queue_order_stats_repopulate_database` to work in a batch mode, perhaps using 100 orders per batch?
- [ ] Add ability to re-process orders based upon a date range. Thinking this could be useful if a specific time period of orders needs to be reprocessed
- [ ] Consider adding a link to the Scheduled Actions tab ( /wp-admin/admin.php?page=wc-status&tab=action-scheduler#/ ) after a job has been queued, so users can view progress of the job
- [ ] Run performance tests of the repopulate job on some limited hosting environments.

**Comment by peterfabian** [comment]
Side note how to run local copy of woo.com: 
https://fieldguide.automattic.com/woocommerce-com-developer-documentation/woothemes-com-setting-up-a-development-environment

**Comment by peterfabian** [comment]
Related issue: https://github.com/woocommerce/wc-admin/issues/429

**Comment by jeffstieler** [comment]
@peterfabian are you working this or does someone else need to pick it up? Looks like https://github.com/woocommerce/wc-admin/pull/1050 hasn't had attention in a bit.
