### ISSUE TITLE
REST API: /reports/coupons should return 'coupon code', 'creation date', 'expiration date' and 'type' for every coupon

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#861]
According to the designs (p6riRB-3dS-p2), we should display 'coupon code', 'creation date', 'expiration date' and 'type' for every coupon in the table summary, but those values are not included in the swaggerhub API examples.

**Comment by peterfabian** [comment]
Please check p7bje6-15o-p2, where this was discussed. Similarly to `categories` endpoint, we would prefer to not duplicate data you can get from `/wc/v3/coupons/{id}`. However, if needed for good reasons, we can add the data to `/reports/coupons` endpoint as well.
