### ISSUE TITLE
Getiing warning when activated plugin.

### ISSUE THREAD

**Issue by baikaresandeep** [woocommerce/wc-admin#874]
I was just getting warnings when I activated the plugin. 

So just get to the root of the cause, i fount that there is no folder of dist

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/csv-export/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 25

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/currency/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 33

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/navigation/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 41

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/date/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 49

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/components/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 68

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/embedded/index.js in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 76

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/components/style.css in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 100

Warning: filemtime(): stat failed for C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin/dist/embedded/style.css in C:\xampp72\htdocs\woo-integration\wp-content\plugins\wc-admin\lib\client-assets.php on line 107

I can see the code to register the script:
       `wp_register_script(
		'wc-csv',
		wc_admin_url( 'dist/csv-export/index.js' ),
		array(),
		filemtime( wc_admin_dir_path( 'dist/csv-export/index.js' ) ),
		true
	);`

and I can't find the folder `/dist/` inside the plugin!

Running: 

WooCommerce version: 3.5.1
WordPress: 4.9.8

Can someone help me on this?

Thanks

**Comment by timmyc** [comment]
Hello @baikaresandeep! Thanks for trying out the plugin. It looks like you may still need to build the plugin code in order for it to work properly - we have some directions on how to do that [here](https://github.com/woocommerce/wc-admin#development).

Alternatively - we are doing a pre-built .zip file release about every two weeks. The first one can be downloaded [here](https://github.com/woocommerce/wc-admin/releases/tag/0.1.0) - but do keep in mind, those snapshots get out of date pretty quickly as new features and bug fixes are merged in here regularly.

Let me know if I can help you get the plugin built locally, or if you have any other questions.
