### ISSUE TITLE
Product report: Incorrect default chart

### ISSUE THREAD

**Issue by LevinMedia** [woocommerce/wc-admin#879]
**Describe the bug**
The product report is currently using the comparison chart when no products are being compared

**To Reproduce**

On the latest version of master, view the products report, and note the chart layout. 

<img width="1721" alt="screen shot 2018-11-16 at 11 51 14 am" src="https://user-images.githubusercontent.com/4500952/48643923-f4b98d00-e995-11e8-8586-c29d99befaf7.png">

**Expected behavior**

The chart should use the standard layout until products are selected and compared. For reference, the screen shot below is the standard layout chart on the revenue report. ( The legend should be in the chart header )

<img width="1735" alt="screen shot 2018-11-16 at 11 52 17 am" src="https://user-images.githubusercontent.com/4500952/48644028-406c3680-e996-11e8-9959-df9bcc655f97.png">

**Comment by Aljullu** [comment]
So, if I understand it correctly, the comparison chart must be shown in these cases:
- _Single product_ + _Variations comparison_/_Top Variations by Items Sold_/_Top Variations by Gross Revenue_
- _Product Comparison_
- _Product Category Comparison_
- _Top Products by Items Sold_

While the standard layout must be displayed in these cases:
- _All products_
- _Single Product_ + _All Variations_

Is it like that @LevinMedia?

**Comment by LevinMedia** [comment]
heya @Aljullu ! Per our slack convo:

**Standard chart**

- Default chart for all reports

**Comparison chart**

- When a user manually selects and compares anything, we switch from standard to comparison (products, categories, coupons, taxes)
- Product detail report (We switch to the product detail report when a user selects a single product using the  "Show single product" filter in the product report, or by clicking the title of a product somewhere in the tabular data. In the product detail report, the product's variations are compared in the comparison chart. For the sake of consistency we still use the comparison chart even if it's a simple product without variations. We treat the simple product as a single variation.)
- any time a user filters a report by "Top" things (IE top products by items sold. This view should also include the select menu that lets a user determine how many top things to show. This is noted in the states section of p6riRB-3jq-p2)
