### ISSUE TITLE
REST API: /reports/categories should return 'category_name' for every category and /reports/categories/stats should return 'categories_count'

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#900]
According to the designs (p6riRB-3dS-p2) some changes must be done to the `categories` endpoints which are not included in SwaggerHub:
- `/reports/categories` should return `category_name` for every category.
- `/reports/categories/stats` should return `categories_count` or there should be some other way to know the total number of categories.

**Comment by peterfabian** [comment]
- as mentioned in p7bje6-151-p2, I assumed the name of category would be fetched from already existing `/products/categories/{id}`, as `/reports/categories` response contains `id` to fetch further info about categories from existing endpoint. If needed, we can add name also to `/reports/categories`, but we would prefer to not duplicate data in different endpoints

- should the `categories_count` show number of categories of products sold in the selected time period or the total of all categories in the shop, irrespective if any products have been sold from the category? Not sure if available in JS, but there is a `X-WP-Total` header returned from `/wp-json/wc/v3/products/categories` that shows total number of categories.

**Comment by Aljullu** [comment]
Thank you for your replies, @peterfabian! I will be answering them in the following days in parallel as I work on them.

> should the categories_count show number of categories of products sold in the selected time period or the total of all categories in the shop, irrespective if any products have been sold from the category? Not sure if available in JS, but there is a X-WP-Total header returned from /wp-json/wc/v3/products/categories that shows total number of all categories.

Thanks for pointing me to that! I saw `/reports/products` also includes the `X-WP-Total` header. Will other endpoints (like `/reports/categories`, `/reports/coupons`, etc.) include it too? In that case, I can use that one which is exactly what I was looking for.

**Comment by peterfabian** [comment]
Yes, `X-WP-Total` should be included in all endpoints.
