### ISSUE TITLE
Switching between chart directions doesn't update the chart width

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#907]
- Go to the _Products_ report.
- Change the filter to _Top Products by Items Sold_.
- Notice the chart overflows.
- Reload the page.
- Change the filter to _All Products_.
- Notice the chart doesn't cover the available space.
![image](https://user-images.githubusercontent.com/3616980/48916096-8c135a00-ee46-11e8-86ac-2363fd2b24f3.png)

**Comment by LevinMedia** [comment]
I'm seeing the same behavior on master. Good catch!
