### ISSUE TITLE
Analytics: Downloads Report Table

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#915]
**Design Post**: p6riRB-3dU-p2
**Mock API**: [https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_downloads_stats](get_reports_downloads_stats)
**REST API Post**: p7bje6-15q-p2

This issue covers creation of the table for the Downloads Report. The REST endpoints needed for this table are still under development ( #428 ) so until that issue ships, this table should use the Swagger Hub mock API.

There is likely going to be a few gaps between the design, and the actual data returned by the endpoint:

- Product Name ( only product_id returned )
- username ( only user_id returned )

Again for now, lets output the data that is being returned by the mock api for both of these scenarios until we come up with an additional solution. We could theoretically query other REST endpoints to get the requisite data, but I'd like to see if we can include some of the needed extended data in the base request first.

**Comment by Aljullu** [comment]
> We could theoretically query other REST endpoints to get the requisite data, but I'd like to see if we can include some of the needed extended data in the base request first.

Considering we only need two extra fields, and they would have to be queried in two different endpoints, I think it makes sense returning those values directly from `reports/downloads`, maybe inside and `extended_info` property.

**Comment by justinshreve** [comment]
@Aljullu I see you are assigned for the table and charts. I just got the full REST API endpoints merged FYI. 

> There is likely going to be a few gaps between the design, and the actual data returned by the endpoint.

You can get this extra information using the `_embed` query parameter. https://developer.wordpress.org/rest-api/using-the-rest-api/linking-and-embedding/#embedding

**Comment by Aljullu** [comment]
Thank you @justinshreve, that looks very good! I already started working on this (#1238) and will have a PR ready next week.
