### ISSUE TITLE
Analytics: Customers Report Table

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#918]
**Design Post**: p6riRB-3dW-p2
**Mock API**: [https://href.li/?https://app.swaggerhub.com/apis/peterfabian/wc-v3-api/1.0.0#/default/get_reports_customers](get_reports_customers)
**REST API Post**: p7bje6-16h-p2

This issue involves creation of the Customers Report Table. Currently the REST API endpoint has yet to be developed ( #916 ), so we will utilize the Swagger Hub mock endpoint for now. There is a desire to not include extended object information in the base reporting endpoint responses ( i.e. only `customer_id` will be returned ). While it will add query complexity to the client side, this report being a simple one seems like one where we could explore requesting the additional data via the current [`/wc/v3/customers`](http://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-a-customer) endpoint.

**Comment by jeffstieler** [comment]
Reopening - table summary still needs to be implemented.
