### ISSUE TITLE
REST API: Create New Stock Report Endpoint

### ISSUE THREAD

**Issue by timmyc** [woocommerce/wc-admin#919]
**Design Post**: p6riRB-3dV-p2

Per the designs, the stock report should be filterable by "Out of Stock", "Low Stock", and "In Stock". The current [products endpoint](http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products) supports a `stock_status` query arg, that accepts the values of `instock`, `outofstock` and `backorder`.

For this issue I'm hoping we can explore adding in support to `/wp-json/wc/v3/products`'s `instock` query arg so you can also filter by "low stock" products.

**Comment by claudiosanches** [comment]
I'm checking and this need to be changed on core.

**Comment by claudiosanches** [comment]
This is something "easy" to do on core: https://github.com/woocommerce/woocommerce/compare/feature/rest-api-products-per-low-level

But looking for the design post, we need to list products and variations at the same time, not possible for `/wp-json/wc/v3/products`, so the best solution is to create a new endpoint for it, probably should have a better performance loading less fields too.

**Comment by timmyc** [comment]
So should I create a new issue to track creation of an entirely new endpoint for the stock report which includes variations too @claudiosanches? Thinking using the existing products endpoint will work for now, and we can update the report when the variant-included endpoint comes online.
