### ISSUE TITLE
Missing /reports/variations/stats endpoint

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/wc-admin#926]
In SwaggerHub there isn't any `/reports/variations/stats` endpoint but according to the designs we need to display some total values for the variations of each product in the table footer (variations sold, items sold, gross revenue and orders):
![image](https://user-images.githubusercontent.com/3616980/48983185-50c89380-f0b1-11e8-8f73-31b89a9f360a.png)

**Comment by claudiosanches** [comment]
`/stats` should help with charts, for this table sounds like that this endpoint can cover most of this fields: https://github.com/woocommerce/wc-admin/pull/930

**Comment by psealock** [comment]
I don't think we'll need `/reports/variations/stats` to power the summary numbers at the bottom of the table.

The chart will be populated by data from `/reports/products/stats` segmented by variations (either all or a comparison). The totals from that response, including headers `'X-WP-Total` and `X-WP-TotalPages`, will correctly reflect variations totals found in `primaryData`.

I am going to close this issue, but if my thinking is at all wrong, @Aljullu please re-open, and we can look into it further.
