### ISSUE TITLE
Analytics: Not loading anything

### ISSUE THREAD

**Issue by msdesign21** [woocommerce/wc-admin#956]
**Describe the bug**
Today was the first day I tried the wc-admin plugin. Going to Analytics, the page loaded is blank (my test site has orders). 

**To Reproduce**
1. Install wc-admin
2. Go to Analytics 

**Expected behavior**
That the Analytics would show

**Screenshots**
@allendav asked me to include this info: 
![http://cld.wthms.co/m6e1te](http://cld.wthms.co/m6e1te+)
Direct Link: http://cld.wthms.co/m6e1te 

Full error text here: http://cld.wthms.co/9Snx2u

![http://cld.wthms.co/J0E2WC](http://cld.wthms.co/J0E2WC+)
Direct Link: http://cld.wthms.co/J0E2WC
 
The index.js script path is: 
`https://testingstorewoo.com/wp-content/plugins/wc-admin-master/dist/csv-export/index.js?ver=4.9.8`

**Desktop (please complete the following information):**
 - OS:  Sierra 10.12.6
 - Browser: Chrome 
 - Version: Version 70.0.3538.102 (Official Build) (64-bit)
- WP Version: WordPress 4.9.8
- Gutenberg version: Version 4.5.1

**Additional context**
This is a .com atomic test site so I can give admin login if needed.

**Comment by timmyc** [comment]
I helped Maria out with this issue, and got the site up and running on the latest pre-built release and all is well
