### ISSUE TITLE
Warnings in admin

### ISSUE THREAD

**Issue by Camilo517** [woocommerce/wc-admin#972]
Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 33

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 41

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 49

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 68

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 76

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 109

Warning: filemtime(): stat failed for /wp-content/plugins/wc-admin-master/lib/client-assets.php on line 116

**Comment by justinshreve** [comment]
Hello @Camilo517!

Thank you for trying out the plugin. Are you using the pre-built zip from [the developer post](https://github.com/woocommerce/wc-admin/releases/tag/v0.2.0)?

Those warnings indicate you may still need to build the plugin code in order for it to work properly. The .zip above handles that for you, or we have some directions on how to do that [here](https://github.com/woocommerce/wc-admin#development).
