### ISSUE TITLE
Removing all filters does not reset query

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/wc-admin#998]
**Describe the bug**
Removing the filters from a comparison by using the "x" does not clear the attributes from the query.

**To Reproduce**

1. Go to `wp-admin/admin.php?page=wc-admin#/analytics/products?filter=compare-products`.
2. Add multiple products to the comparison and click "Compare".
3. Remove those products using the "x" next to each.
4. Note that the URL still contains the the filter query `products?filter=compare-products&products=xxxxxxx`

**Expected behavior**
Removing all products (or maybe anything < 2 in the case of the comparison filter) should remove this filter.  To remove these filters, you'll either need to switch to another filter or add the products back and click "Clear all."

**Screenshots**
<img width="490" alt="screen shot 2018-12-05 at 2 24 53 pm" src="https://user-images.githubusercontent.com/10561050/49494319-3f923a80-f89a-11e8-8fcf-068b7df8ae1a.png">

**Comment by psealock** [comment]
>Note that the URL still contains the the filter query

I think this is expected behaviour. Similarly, comparing multiple products, then adding an extra product won't update the url either until "compare" is clicked again.

But if you "x" out of all of them, adding them back isn't ideal. Thats a bug for sure.

**Comment by joshuatf** [comment]
Agreed.  Since we have the option to "Clear" (which will remove URL params) if there are filters selected, this felt a bit odd and I was expecting one of a couple things to happen:
* The "Clear" button would remain even after the filters are removed so we can get back to the original state.
* The filter params are cleared when the final filter is removed.

Another option would be to update automatically on filter change instead of the need for the "Compare" button ([Google Trends](https://trends.google.com) comes to mind), but maybe this goes against WordPress UI patterns.

/cc @LevinMedia

**Comment by LevinMedia** [comment]
Under most circumstances - the current behavior is the expected behavior. 

As @joshuatf pointed out in a Slack convo, things get weird when you when you add a bunch of items to a filter, then manually X out of ALL of them. You're left with the filter params in the URL, and really no way to get rid of them. 

In that case (X-ing out all of the filter items manually), it should follow same behavior as clicking the "clear all" link.

**Comment by timmyc** [comment]
Closing this out as it sounds like the behavior is expected. If i'm incorrect, please re-open.
